### PR TITLE
optimize: optimize seata client I/O processing by adjusting thread count

### LINKED ISSUE #7168: The client's NioEventLoopGroup thread is only 1 by default
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

Image

Image

The io reading and coding/decoding work of the seata client is in this thread, the default thread of 1 will affect the efficiency of its processing, we need to adjust it to the number of threads of cpu*2, you can change the default value to `WorkThreadMode.Default.getValue()`

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by YongGoose**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #7168

### CODE REVIEW

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/blob/2.x/script/client/conf/file.conf#L44
https://github.com/apache/incubator-seata/blob/2.x/script/client/spring/application.properties#L74
https://github.com/apache/incubator-seata/blob/2.x/script/client/spring/application.yml#L85
https://github.com/apache/incubator-seata/blob/2.x/script/config-center/config.txt#L35
Since the corresponding IO thread count for the client in the above files is 1, I believe these configurations should be changed to -1. Then, in the code, handle the value of -1 by converting it to the number of CPU cores * 2.

File: core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java [hunk 1]
```diff
@@ -25,7 +25,6 @@
 import static org.apache.seata.common.DefaultValues.DEFAULT_RPC_RM_REQUEST_TIMEOUT;
 import static org.apache.seata.common.DefaultValues.DEFAULT_RPC_TM_REQUEST_TIMEOUT;
 import static org.apache.seata.common.DefaultValues.DEFAULT_SELECTOR_THREAD_PREFIX;
-import static org.apache.seata.common.DefaultValues.DEFAULT_SELECTOR_THREAD_SIZE;
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:28]: The value of DEFAULT_SELECTOR_THREAD_SIZE should be changed to -1

Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:28]: Done in https://github.com/apache/incubator-seata/pull/7170/commits/f5d38a93014946cf08a563a4b37c44b9e8687b5c !

**Comment by YongGoose** [comment]
> Then, in the code, handle the value of -1 by converting it to the number of CPU cores * 2.

What do you think about changing the thread count to CPU cores * 2 when the value is negative?

File: core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java (hunk 1 above)
Comment (funky-eyes) [reply core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:28]: > Done in [f5d38a9](https://github.com/apache/incubator-seata/commit/f5d38a93014946cf08a563a4b37c44b9e8687b5c) !

In NettyClientBootstrap, it is necessary to handle the case where selectorThreadSizeThreadSize=-1.

Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:28]: > > Done in [f5d38a9](https://github.com/apache/incubator-seata/commit/f5d38a93014946cf08a563a4b37c44b9e8687b5c) !
> 
> In NettyClientBootstrap, it is necessary to handle the case where selectorThreadSizeThreadSize=-1.

- https://github.com/apache/incubator-seata/pull/7170#issuecomment-2667623948

What do you think?

**Comment by funky-eyes** [comment]
> What do you think about changing the thread count to CPU cores * 2 when the value is negative?

If it is a negative number, directly assign the value of `WorkThreadMode.Default.getValue()` to it

File: core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java [hunk 2]
```diff
@@ -346,11 +345,13 @@ public static String getSocketAddressStartChar() {
...
      * Gets client selector thread size.
+     * If the configured thread size is less than or equal to 0, it returns the default value.
      *
-     * @return the client selector thread size
+     * @return the client selector thread size, or the default value if the configured size is invalid.
      */
     public int getClientSelectorThreadSize() {
-        return CONFIG.getInt(ConfigurationKeys.CLIENT_SELECTOR_THREAD_SIZE, DEFAULT_SELECTOR_THREAD_SIZE);
+        int threadSize = CONFIG.getInt(ConfigurationKeys.CLIENT_SELECTOR_THREAD_SIZE, WorkThreadMode.Default.getValue());
+        return threadSize > 0 ? threadSize : WorkThreadMode.Default.getValue();
```
Comment (YongGoose) [inline core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:354]: @funky-eyes 

Handling this in `NettyClientBootstrap` is a good idea, but I believe it is more appropriate to process it here.
Because if we handle this in `NettyClientBootstrap`, we would need to process` -1` in every piece of code that retrieves the thread count using this method.

Comment (funky-eyes) [reply core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientConfig.java:354]: You are right, handling it this way is better, good job.

**Comment by YongGoose** [comment]
@funky-eyes 

I have resolved the failing test related to `getClientSelectorThreadSize`.
However, the `testRemoveConfig` test in `ZkConfigurationTest` is still failing, but only when running on `Java 8`.
Could you help me understand why this failure occurs specifically in `Java 8`?

**Comment by funky-eyes** [comment]
> @funky-eyes
> 
> I have resolved the failing test related to `getClientSelectorThreadSize`. However, the `testRemoveConfig` test in `ZkConfigurationTest` is still failing, but only when running on `Java 8`. Could you help me understand why this failure occurs specifically in `Java 8`?

This is not caused by your PR; this issue is an occasional occurrence, and the exact cause is currently unknown. I have restarted the CI workflow for now.
