### PR TITLE
bugfix: fix XA rollback on commit failure (#6492)

### LINKED ISSUE #6492: XA 模式一个分支超时，会把IDLE 连接放回连接池，导致其他业务执行异常
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
开启 XA 全局事务后，如果其中一条 SQL 执行超时，会导致该分支回滚失败，并且以  `IDLE ` 的状态放回连接池，后续再执行 SQL 会报错。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 开启全局事务
2. 执行分支事务 A，对记录 a 修改
3. 执行分支事务 B，同样对记录 a 进行修改，但是由于 A 事务未完成，死锁导致阻塞。
4. TC 检测到全局事务超时，让各分支事务回滚：事务 A 回滚成功，事务 B 由于还在执行中，回滚失败（不断刷回滚失败日志: `NO_TA` 错误，因为 B 事务还没 `XA prepare`）
5. 由于事务 A 已回滚，事务 B 继续执行，然后尝试 `commit`，先 `XA end` 再向 TC 查询状态，由于分布式事务已经没了，报错
6. 报错之后尝试 `rollback`，rollback 时再次执行 `XA end`，mysql 返回错误 `XAER_RMFAIL: The command cannot be executed when global transaction is in the IDLE state`，回滚失败
7. 至此，当前连接处于 `IDLE` 状态，没有 `XA rollback` 成功

根本问题时因为 commit 的时候已经 `XA end` 过一次了，rollback 的时候又想 `XA end` 一次，中断了 rollback 过程。

### Ⅴ. Anything else we need to know?
建议方案:
1. 执行完 sql 后，commit 之前先向 TC 确认一次事务状态，如果事务已经过期了，直接执行 rollback
2. rollback 时执行 `XA end` 之后如果 sql 报错是 `IDLE` 错误，忽略该错误继续 `XA rollback`

如果认定这是一个 bug，我可以尝试提交修改的 PR 😀

### Ⅵ. Environment:

- JDK version(e.g. `java -version`): 11
- Seata client/server version:  1.8.0
- Database version: 8.0.29

### PR DESCRIPTION
**Pull request by tanyaofei**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
修复 XA 模式下执行长时间 SQL(或死锁 SQL) 没有完成回滚就 `close`

### Ⅱ. Does this pull request fix one issue?

fixes #6492 

### Ⅴ. Special notes for reviews
1. `autoCommit = true` 的情况下 `SQLSTATE_XA_NOT_END` 可以避免 `ExecuteTemplateXA` 再次 `rollback`
2. `autoCommit = false` 的情况下不会 doRollbackOnCommitException

### CODE REVIEW

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/xa/ConnectionProxyXA.java [hunk 1]
```diff
@@ -224,6 +230,10 @@ public synchronized void commit() throws SQLException {
 
     @Override
     public void rollback() throws SQLException {
+        rollback(true);
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/xa/ConnectionProxyXA.java]: 我建议定义一个成员变量来替代这个方法入参,并且这变量要在close时进行重置,避免被连接池复用时参数错误
I suggest defining a member variable to replace the imported parameter of this method, and this variable should be reset at close to avoid parameter errors when reused by the connection pool

File: changes/en-us/2.x.md
Comment (funky-eyes) [inline changes/en-us/2.x.md:1]: 再补充下作者信息到2.x.md中
Add author information to 2.x.md

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/xa/ConnectionProxyXA.java (hunk 1 above)
Comment (tanyaofei) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/xa/ConnectionProxyXA.java]: 有道理。已经修改了，加了一个 `xaEnd()` 的方法来封装 XA End 的调用

**Review by funky-eyes — APPROVED** [review]
LGTM
Please send your DingTalk account to my email address `jianbin@apache.org`, and I will invite you to join the Seata developer group.
