### PR TITLE
bugfix: prevent Netty I/O thread blocking by async channel release via reconnectExecutor

### LINKED ISSUE #7497: The client I/O thread may be blocked
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [ ] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

Image

Image

Image
在 NettyClientChannelManager.java 中，releaseChannel 方法和 acquireChannel 方法都会对 channelLocks 对象进行加锁。exceptionCaught 方法（位于 AbstractNettyRemotingClient.java 的内部类 ClientHandler 中）会调用 releaseChannel。而exceptionCaught是出于netty的io线程中，如果io线程核心数只有1，则会导致请求和接受响应的线程一并阻塞，导致流量跌零。当然只有当服务端非优雅下线时，并且恰好reconnect任务与执行exceptionCaught方法同时进行才会导致这个现象，因为服务端节点宕机后已经无法连接了，该同步锁会等待建立连接请求超时才会释放该锁，导致这个期间客户端的请求全部hang住
In NettyClientChannelManager.java, both the releaseChannel method and acquireChannel method acquire locks on the channelLocks object. The exceptionCaught method (located in the inner class ClientHandler of AbstractNettyRemotingClient.java) calls releaseChannel. Since exceptionCaught runs in Netty's I/O thread, if there's only 1 I/O thread core, it will cause both request and response handling threads to be blocked simultaneously, resulting in zero traffic throughput. This phenomenon only occurs when the server shuts down ungracefully and the reconnect task happens to run concurrently with the exceptionCaught method execution. Because the server node is down and no longer connectable, the synchronization lock will wait until the connection establishment request times out before releasing the lock, causing all client requests to hang during this period.

另外channelLocks似乎永远不会进行清理，当服务端在k8s中部署，每次重启都更换一个新的ip时，久而久之客户端就会面临oom的风险。
Additionally, channelLocks seems to never be cleaned up. When the server is deployed in Kubernetes and gets a new IP address with each restart, over time the client will face the risk of OOM (Out of Memory).

### Ⅱ. Describe what happened

_No response_

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

_No response_

### PR DESCRIPTION
**Pull request by Dltmd202**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

Fixes a potential Netty I/O thread blocking issue by executing `releaseChannel()` asynchronously via a dedicated `reconnectExecutor` thread pool.

Also ensures proper shutdown of `reconnectExecutor` to avoid thread leaks.

### Ⅱ. Does this pull request fix one issue?

fixes #7497

### Ⅴ. Special notes for reviews
- Naming conventions (`rpcReconnectExecutor`) aligned with existing merge thread patterns.
- `reconnectExecutor` is now managed with proper init and destroy lifecycle hooks.

### CODE REVIEW

File: core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java [hunk 1]
```diff
@@ -137,6 +140,13 @@ public void init() {
                     new NamedThreadFactory(getThreadPrefix(), MAX_MERGE_SEND_THREAD));
             mergeSendExecutorService.submit(new MergedSendRunnable());
         }
+        reconnectExecutor = new ThreadPoolExecutor(
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: Why not use the timerExecutor thread pool directly?

Comment (Dltmd202) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: Hi @funky-eyes
I added a separate thread pool mainly to give it a clear thread name, so it’s easier to trace when reconnect-related issues happen. But if that feels unnecessary here, I’m happy to switch to using the existing `timerExecutor`. Let me know what you think!

Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: IMO, creating a new thread pool is generally preferred when there’s a high-priority task or when real-time processing is critical. Also, how frequently the issue occurs can be an important factor in deciding whether to create a new thread pool.

From a simple traceability standpoint, the current `timeoutExecutor` is used in several places — such as handling reconnections and removing timed-out messages.

So, it might make sense to update the prefix to something more general that fits well across all these usages, and reuse it accordingly.

Comment (funky-eyes) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: > Hi @funky-eyes I added a separate thread pool mainly to give it a clear thread name, so it’s easier to trace when reconnect-related issues happen. But if that feels unnecessary here, I’m happy to switch to using the existing `timerExecutor`. Let me know what you think!

I wrote very clearly in the issue why we should reuse the timeoutExecutor. I suggest you can take a look at the reason.

Comment (Dltmd202) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: Thanks for pointing that out. I revisited the issue and I now see your point more clearly — reusing timeoutExecutor makes sense, especially since it’s already used for similar tasks like handling reconnections and timeouts. Avoiding an extra thread pool also helps keep things lean and easier to manage.

I’ll go ahead and update the code to reuse timeoutExecutor accordingly. Appreciate the feedback!

Comment (Dltmd202) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java]: I’ve finished the changes. Would you mind taking a look when you have time?
@funky-eyes @YongGoose

**Review by funky-eyes — APPROVED** [review]
LGTM

File: core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java [hunk 2]
```diff
@@ -143,6 +145,26 @@ void testCleanupWithNullChannel() {
...
+        channelManagerField.setAccessible(true);
+        NettyClientChannelManager originalManager = (NettyClientChannelManager) channelManagerField.get(client);
+
+        NettyClientChannelManager spyManager = spy(originalManager);
+        channelManagerField.set(client, spyManager);
+
+        handler.exceptionCaught(mockCtx, new IllegalArgumentException("test"));
+
+        Thread.sleep(500);
+        verify(spyManager).releaseChannel(eq(channel), anyString());
```
Comment (YongGoose) [inline core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java]: Is there a specific reason you used `anyString()`?
It seems like serverAddress will always be `127.0.0.1:8091`, so I’m wondering if matching the exact value would be more appropriate.

**Comment by PeppaO** [comment]
This modification cannot solve the problem. I think you can reproduce the problem first, then analyze the cause, and retest after modification.

**Comment by PeppaO** [comment]
To reproduce, start three tc nodes 8091/8092/8093, start a business-xa application, observe the corresponding tcp connection port, then kill 8091, and observe whether the tcp connection is disconnected and reconnected

**Comment by PeppaO** [comment]
After resolving the disconnection and reconnection, perform a stress test to see if the TPS is 0 during the shutdown period after killing one of the tc nodes.
@funky-eyes @Dltmd202

**Review by funky-eyes — COMMENTED** [review]
All places in ChannelHandler that call the clientChannelManager.releaseChannel method need to be made asynchronous.

File: core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java (hunk 2 above)
Comment (Dltmd202) [reply core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java]: You’re right — that makes sense to me as well. I’ll go ahead and update it to match the exact value instead of using `anyString()`.

**Comment by funky-eyes** [comment]
18.18% of diff hit (target 60.50%)
Can you add some test cases to improve the coverage?

**Comment by Dltmd202** [comment]
Sure, I’ll take care of it!

**Comment by Dltmd202** [comment]
I’ve finished the changes. Would you mind taking a look when you have time?
@funky-eyes
