### PR TITLE
bugfix: remove the condition that IPv6 must start with fe80:

### LINKED ISSUE #7110: 2409:8a5c:6730:4490:f0e8:b9ad:3b3d:e739%br0 should be a valid ipv6
NetAddressValidatorUtil.isIPv6Address("2409:8a5c:6730:4490:f0e8:b9ad:3b3d:e739%br0") return false, but the ip is return by program and should be valid.

With this issue, preferredNetworks not work for ipv6.

### PR DESCRIPTION
**Pull request by xiaoxiangyeyu0**
…x will not be checked. remove starting with "fe80:"

- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/apache/incubator-seata/issues/7110

### CODE REVIEW

File: common/src/main/java/org/apache/seata/common/util/NetAddressValidatorUtil.java [hunk 1]
```diff
@@ -133,19 +129,17 @@ public static boolean isIPv6IPv4MappedAddress(final String input) {
...
      * @return true if address part of <code>input</code> is in correct IPv6 notation.
      */
     public static boolean isLinkLocalIPv6WithZoneIndex(String input) {
-        if (input.length() > FIVE && input.substring(ZERO, FIVE).equalsIgnoreCase(FE80)) {
-            int lastIndex = input.lastIndexOf(PERCENT);
-            if (lastIndex > ZERO && lastIndex < (input.length() - 1)) {
-                String ipPart = input.substring(ZERO, lastIndex);
-                return isIPv6StdAddress(ipPart) || isIPv6HexCompressedAddress(ipPart);
-            }
+        int lastIndex = input.lastIndexOf(PERCENT);
```
Comment (funky-eyes) [inline common/src/main/java/org/apache/seata/common/util/NetAddressValidatorUtil.java:139]: 请增加一个测试用例
Please add a test case

Comment (xiaoxiangyeyu0) [reply common/src/main/java/org/apache/seata/common/util/NetAddressValidatorUtil.java:139]: 新增isLinkLocalIPv6WithZoneIndex方法测试用例

**Review by funky-eyes — APPROVED** [review]
LGTM
请将pr登记至2.x.md的中英两版文件中

**Review by xingfudeshi — APPROVED** [review]
LGTM
