### PR TITLE
optimize: optimize the retry logic in the acquireMetadata method

### LINKED ISSUE #6097: When all Raft nodes are offline, it will retry indefinitely after the maximum metadata delay is reached.
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
image
image
metadataMaxAgeMs默认为30s，当所有节点不可用超过30s后，会因为metadataMaxAgeMs超时，导致无限重试获取元数据，而不会进行sleep 一秒来等待。要求统一watch和acquireClusterMetaData，统一在while(true)中进行对可重试的异常进行等待重试
The default value of metadataMaxAgeMs is 30 seconds. When all nodes become unavailable for over 30 seconds, an infinite retry loop will be triggered for metadata retrieval due to the metadataMaxAgeMs timeout, without waiting for a one-second sleep. It is required to unify the handling of retryable exceptions for both watch and acquireClusterMetaData within a while(true) loop for waiting and retrying.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by ggbocoder**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
fixes #6097

### CODE REVIEW

File: discovery/seata-discovery-raft/src/main/java/io/seata/discovery/registry/raft/RaftRegistryServiceImpl.java [hunk 1]
```diff
@@ -169,30 +169,37 @@ protected static void startQueryMetadata() {
...
+                                if (fetch) {
+                                    for (String group : METADATA.groups(clusterName)) {
+                                        try {
+                                            acquireClusterMetaData(clusterName, group);
+                                        } catch (Exception e) {
+                                            // prevents an exception from being thrown that causes the thread to break
+                                            LOGGER.error("failed to get the leader address,error: {}", e.getMessage());
+                                            if (e instanceof RetryableException) {
+                                                throw e;
+                                            }
```
Comment (funky-eyes) [inline discovery/seata-discovery-raft/src/main/java/io/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]:
```suggestion
                                            if (e instanceof RetryableException) {
                                                throw e;
                                            } else {
                                                LOGGER.error("failed to get the leader address,error: {}", e.getMessage());
                                            }
```

**Review by funky-eyes — APPROVED** [review]
LGTM
