### PR TITLE
bugfix: fix the bug where Role.participant does not execute hooks but clears them. 

### LINKED ISSUE #6384: 2.0.0 Role.Participant不执行hook但会清理，导致hook无法执行
### Ⅰ. Issue Description
image
如题
https://github.com/apache/incubator-seata/issues/5595 这个修复引起的

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  2.0.0
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by jonasHanhan**
… clears them.

- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
bugfix: fix the bug where Role.participant does not execute hooks but clears them. 

### Ⅱ. Does this pull request fix one issue?

fixes #6384

### CODE REVIEW

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java [hunk 1]
```diff
@@ -733,7 +733,7 @@ public void clearUp() {
         RootContext.unbind();
         RootContext.unbindBranchType();
         if (sagaTransactionalTemplate != null) {
-            sagaTransactionalTemplate.cleanUp();
+            sagaTransactionalTemplate.cleanUp(null);
```
Comment (funky-eyes) [inline saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: Since the globalTransaction is passed above, theoretically, they should all go to it and pass the globalTransaction

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/tm/DefaultSagaTransactionalTemplate.java [hunk 2]
```diff
@@ -273,8 +273,10 @@ public void setApplicationContext(ApplicationContext applicationContext) throws
     }
 
     @Override
-    public void cleanUp() {
-        TransactionHookManager.clear();
+    public void cleanUp(GlobalTransaction tx) {
+        if (tx == null || tx.getGlobalTransactionRole() == GlobalTransactionRole.Launcher) {
```
Comment (funky-eyes) [inline saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/tm/DefaultSagaTransactionalTemplate.java]: I don't think it should be null, since it should be strictly judged to clean up the hook, if it's null it should throw an exception prompting the message that the value is not allowed to be null
我认为不应该为null，既然要清理hook，应该是严格判断的，如果为null应该抛出异常提示该值不允许为null的信息

File: tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java [hunk 3]
```diff
@@ -385,8 +385,10 @@ private void triggerAfterCompletion(GlobalTransaction tx) {
         }
     }
 
-    private void cleanUp() {
-        TransactionHookManager.clear();
+    private void cleanUp(GlobalTransaction tx) {
+        if (tx == null || tx.getGlobalTransactionRole() == GlobalTransactionRole.Launcher) {
```
Comment (funky-eyes) [inline tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java]: ibid

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java [hunk 4]
```diff
@@ -729,11 +729,26 @@ public List<StateInstance> queryStateInstanceListByMachineInstanceId(String stat
...
-    public void clearUp() {
+    public void clearUp(StateMachineInstance machineInstance, ProcessContext context) {
         RootContext.unbind();
         RootContext.unbindBranchType();
         if (sagaTransactionalTemplate != null) {
-            sagaTransactionalTemplate.cleanUp();
+            GlobalTransaction globalTransaction;
+            try {
+                globalTransaction = getGlobalTransaction(machineInstance, context);
+                if (globalTransaction == null) {
```
Comment (funky-eyes) [inline saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: Why not unify it in template?

Comment (jonasHanhan) [reply saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: Do you mean to move the getGlobalTransaction method to the template? If so, it should be a refactoring of the code and should not be done in this commit.
你的意思是把getGlobalTransaction 方法移动到模版里么 如果这样的话应该是对代码的一次重构,不应该在本次提交中完成

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java [hunk 5]
```diff
@@ -729,11 +729,26 @@ public List<StateInstance> queryStateInstanceListByMachineInstanceId(String stat
     }
 
     @Override
-    public void clearUp() {
+    public void clearUp(StateMachineInstance machineInstance, ProcessContext context) {
```
Comment (ptyin) [inline saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java:732]: You dont need to add `StateMachineInstance machineInstance` to method signature, use `(StateMachineInstance) context.getVariable(DomainConstants.VAR_NAME_STATEMACHINE_INST)` to get it instead.

It is more natrual to use `ProcessContext` to pass variables.

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java [hunk 6]
```diff
@@ -729,11 +729,27 @@ public List<StateInstance> queryStateInstanceListByMachineInstanceId(String stat
...
+                            FrameworkErrorCode.ObjectNotExists);
+                }
+                sagaTransactionalTemplate.cleanUp(globalTransaction);
+            } catch (ExecutionException e) {
+                LOGGER.error("Report transaction finish to server error: {}, StateMachine: {}, XID: {}, Reason: {}",
+                        e.getCode(), machineInstance.getStateMachine().getName(), machineInstance.getId(), e.getMessage(), e);
+            } catch (TransactionException e) {
+                LOGGER.error("Report transaction finish to server error: {}, StateMachine: {}, XID: {}, Reason: {}",
+                        e.getCode(), machineInstance.getStateMachine().getName(), machineInstance.getId(), e.getMessage(), e);
+            }
```
Comment (ptyin) [inline saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: First, there is no need to throw `ExecutionException` and re-catch it, and I prefer not to log error for "global transaction not found".
Besides, it is not possible for these lines to throw `TransactionException`. Remove it in case to confuse others.

In one word, it would be nice to remove these loggings.

Comment (ptyin) [reply saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: Sry, I miss one line above. Dont care about these comments.

File: saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java (hunk 4 above)
Comment (funky-eyes) [reply saga/seata-saga-spring/src/main/java/org/apache/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java]: > Do you mean to move the getGlobalTransaction method to the template? If so, it should be a refactoring of the code and should not be done in this commit. 你的意思是把getGlobalTransaction 方法移动到模版里么 如果这样的话应该是对代码的一次重构,不应该在本次提交中完成

我说的是在template中针对传入globaltransactional进行判空,如果是空的应该抛异常提示不允许为null
I'm talking about passing in globaltransactional in the template for null, if it's null it should throw an exception to indicate that it's not allowed to be null.

**Review by ptyin — APPROVED** [review]
LGTM

File: tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java (hunk 3 above)
Comment (funky-eyes) [inline tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java]: Why does DefaultSagaTransactionalTemplate.java do the processing, but no exception is thrown here?
为什么DefaultSagaTransactionalTemplate.java做了处理,而这里没有进行抛出异常?

Comment (jonasHanhan) [reply tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java]: private void cleanUp(GlobalTransaction tx) {
        if (tx == null) {
            throw new FrameworkException("Global transaction does not exist. Unable to proceed without a valid global transaction context.",
                    FrameworkErrorCode.ObjectNotExists);
        }
        if (tx.getGlobalTransactionRole() == GlobalTransactionRole.Launcher) {
            TransactionHookManager.clear();
        }
    }
Is this suitable?

Comment (jonasHanhan) [reply tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java]: I have repaired it in this way, please review.

**Review by funky-eyes — APPROVED** [review]
LGTM
