### PR TITLE
bugfix: in dubbo 3.x version, the consumer can't generate tcc proxy.

### LINKED ISSUE #6096: Question: Seata与Dubbo整合如何开启TCC自动代理？
# 问题描述

我使用Seata与Dubbo整合的demo，在阅读Seata文档的时候看到如果Seata和Dubbo配合使用无需使用`@LocalTCC`注解。

> @LocalTCC注解用来表示实现了二阶段提交的本地的TCC接口。如果使用Dubbo作为RPC通信组件则无须用此注解。

但是当我去除掉`@LocalTCC`的时候则发现无法进行代理。

追踪源码发现在`GlobalTransactionScanner.wrapIfNecessary`方法中`TCCBeanParserUtils.isTccAutoProxy(bean, beanName, applicationContext)`并没有为`true`

在其中发现`DubboRemotingParser.isReference`和`isRemotingFactoryBean`中调用的`!SpringProxyUtils.isProxy(bean)`均没有识别到代理

请问应该如何进行配置才能使用Dubbo的TCC自动代理呢？

### LINKED ISSUE #6099: in tcc rpc mode, consumer can't generated proxy as normal, so it doesn't work.
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
1. in tcc rpc mode, consumer can't generated proxy as normal, so it doesn't work. 
在tcc rpc 模式下，consumer端不能正常生成代理，因此tcc不能正常工作.
original issue come from https://github.com/seata/seata/issues/6096

2. int tcc rpc mode, when send the order of the second stage in tc. it can't find the channel of provider rm.
在tcc rpc 模式下，当下发二阶段的指令时，不能找到生产者的RM channel

### Ⅱ. Describe what happened
1.  in tcc rpc mode, when rpc consumer generate proxy, there is a check which is incorrect to filtered factorybean.
在tcc rpc模式下，当rpc消费者端生成代理时，check操作不正确的过滤掉了factorybean.
image
image

2. when search the provider address to send the order of the second stage in TC at TCC mode，tryOtherApp is false , applicationIdMap is server rm applicationId and address map, targetApplicationId is consumer's applicationId, so it can't get the consumer address correctly.
当在TC端TCC模式下查找生产者地址下发二阶段指令时，tryOtherApp 是false状态，applicationIdMap 是server端 rm applicationId 和 地址的映射，targetApplicationId 是消费者端的applicationId，因此不能正确获取到消费者端的地址
image
image

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
4. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by laywin**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
https://github.com/seata/seata/issues/6099

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/seata/seata/issues/6099
fixes #6096

### CODE REVIEW

File: integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java [hunk 1]
```diff
@@ -34,6 +34,8 @@ private DubboUtil() {
     private static final String ALIBABA_DUBBO_PROXY_NAME_PREFIX = "com.alibaba.dubbo.common.bytecode.proxy";
     private static final String APACHE_DUBBO_PROXY_NAME_PREFIX = "org.apache.dubbo.common.bytecode.proxy";
 
+    private static final String DUBBO_3_X_PARTIAL_PROXY_NAME = "DubboProxy";
```
Comment (funky-eyes) [inline integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java:37]: Can you only use contains? and not startsWith or endsWith?
只能使用contains？而不是startsWith或者endsWith吗？

File: core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java [hunk 2]
```diff
@@ -399,7 +400,7 @@ public static Channel getChannel(String resourceId, String clientId, boolean try
             }
         }
 
-        if (resultChannel == null && tryOtherApp) {
+        if (resultChannel == null && BranchType.TCC == branchType) {
```
Comment (funky-eyes) [inline core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: 为什么要改变入参，而不是在由调用方决定是否开启tryOtherApp
Why change the entry parameter when it's up to the caller to turn on tryOtherApp?

File: integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java (hunk 1 above)
Comment (laywin) [reply integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java:37]: image

there is no fixed prefix or suffix in generated proxy name,  i will try later to concat a prefix to judge.
生成代理名字的时候没有固定的前缀和后缀，我看能不能凭借一个前缀来判断.

File: core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java (hunk 2 above)
Comment (laywin) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: i feel the place convention over configuration is better, method signature is better understood without loss of flexibility.
这个地方感觉用 预定大于配置 的方法更好一点，不失灵活性的同时方法签名也更好理解.

Comment (funky-eyes) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: > i feel the place convention over configuration is better, method signature is better understood without loss of flexibility. 这个地方感觉用 预定大于配置 的方法更好一点，不失灵活性的同时方法签名也更好理解.

I'm not sure if there are any other branch types that need this in the future, but if they all rely on an internal if || it's just too low.
未来不确定有没有其他的分支类型需要这种，如果都靠内部一个if || 这种写法太low了

Comment (slievrly) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: What about tryOtherApp in AT transaction mode? The original logic is that only AT mode can go here, now only TCC mode can go here?

Comment (laywin) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: > What about tryOtherApp in AT transaction mode? The original logic is that only AT mode can go here, now only TCC mode can go here?

yeah, because of TCC rpc mode regiter branch in constomer, send order of TC two stage to provider. so it can't find the channel as normal, so tcc model will try other app. @funky-eyes 's opinion there may be a risk in at to find a same resource diff app channel, ex: two instance have status.

是的，因为TCC RPC模式是在消费者端注册分支，TC在二阶段下发指令给服务者端。导致通过消费者端的app去找服务者端的channel的时候会失败，所以tcc 模式会尝试其他app channel. @funky-eyes 的建议在AT模式下发指令到相同资源不同app的端可能存在风险, 比如两台实例可能有状态的情况下.

Comment (laywin) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: > > i feel the place convention over configuration is better, method signature is better understood without loss of flexibility. 这个地方感觉用 预定大于配置 的方法更好一点，不失灵活性的同时方法签名也更好理解.
> 
> I'm not sure if there are any other branch types that need this in the future, but if they all rely on an internal if || it's just too low. 未来不确定有没有其他的分支类型需要这种，如果都靠内部一个if || 这种写法太low了

no problem, i will rollback.

File: server/src/main/java/io/seata/server/coordinator/AbstractCore.java [hunk 3]
```diff
@@ -192,7 +192,7 @@ protected BranchStatus branchCommitSend(BranchCommitRequest request, GlobalSessi
                                             BranchSession branchSession) throws IOException, TimeoutException {
 
         BranchCommitResponse response = (BranchCommitResponse) remotingServer.sendSyncRequest(
-            branchSession.getResourceId(), branchSession.getClientId(), request, branchSession.isAT());
+            branchSession.getResourceId(), branchSession.getClientId(), request, branchSession.getBranchType() == BranchType.TCC);
```
Comment (pengten) [inline server/src/main/java/io/seata/server/coordinator/AbstractCore.java]: What is the purpose of this change?

File: core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java (hunk 2 above)
Comment (pengten) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: > > What about tryOtherApp in AT transaction mode? The original logic is that only AT mode can go here, now only TCC mode can go here?
> 
> yeah, because of TCC rpc mode regiter branch in constomer, send order of TC two stage to provider. so it can't find the channel as normal, so tcc model will try other app. @funky-eyes 's opinion there may be a risk in at to find a same resource diff app channel, ex: two instance have status.
> 
> 是的，因为TCC RPC模式是在消费者端注册分支，TC在二阶段下发指令给服务者端。导致通过消费者端的app去找服务者端的channel的时候会失败，所以tcc 模式会尝试其他app channel. @funky-eyes 的建议在AT模式下发指令到相同资源不同app的端可能存在风险, 比如两台实例可能有状态的情况下.

Maybe this is not the scope of this bugfix.

Comment (laywin) [reply core/src/main/java/io/seata/core/rpc/netty/ChannelManager.java]: > > > What about tryOtherApp in AT transaction mode? The original logic is that only AT mode can go here, now only TCC mode can go here?
> > 
> > 
> > yeah, because of TCC rpc mode regiter branch in constomer, send order of TC two stage to provider. so it can't find the channel as normal, so tcc model will try other app. @funky-eyes 's opinion there may be a risk in at to find a same resource diff app channel, ex: two instance have status.
> > 是的，因为TCC RPC模式是在消费者端注册分支，TC在二阶段下发指令给服务者端。导致通过消费者端的app去找服务者端的channel的时候会失败，所以tcc 模式会尝试其他app channel. @funky-eyes 的建议在AT模式下发指令到相同资源不同app的端可能存在风险, 比如两台实例可能有状态的情况下.
> 
> Maybe this is not the scope of this bugfix.

tcc rpc mode can't find the channel, if no this change.

**Review by slievrly — CHANGES_REQUESTED** [review]
I cannot agree with this plan. Consider what would happen if there were no multi-tenancy isolation in TCC.

**Comment by funky-eyes** [comment]
> I cannot agree with this plan. Consider what would happen if there were no multi-tenancy isolation in TCC.

A long time ago, the version is to allow tcc to be sent to other apps, and in the consumer side of the first stage of registration, the second stage in the provider side of the submission rely on this function, this pr just restore the previous practice
很久以前的版本就是允许tcc下发的其他的app中，而且在consumer侧一阶段注册，二阶段在provider侧提交靠的就是这个功能，这个pr只是还原了以前的做法

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
LGTM

File: integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java (hunk 1 above)
Comment (slievrly) [reply integration-tx-api/src/main/java/io/seata/integration/tx/api/util/DubboUtil.java:37]: Deeply analyzing the source code is really excellent.
