### PR TITLE
bugfix: fix could not rollback when insert the table with multiple key

### LINKED ISSUE #6076: Could not rollback when insert the table with multiple key
### Ⅰ. Issue Description
the primary key is `id` and `user_id`
`insert into account_tbl_multi_pk(user_id, money, sex, information, create_time) values (?, ?, ?, ?, ?)`
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by l81893521**
- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?
fixes #6076

### CODE REVIEW

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 1]
```diff
@@ -521,17 +521,22 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
...
             if (!containsPK(table, unescapeColumns)) {
                 List<String> pkNameList = tableMeta.getEscapePkNameList(getDbType());
+
                 if (CollectionUtils.isNotEmpty(pkNameList)) {
-                    if (StringUtils.isNotBlank(tableAlias)) {
-                        needUpdateColumns.add(getColumnNamesWithTablePrefix(table, tableAlias, pkNameList));
-                    } else {
-                        needUpdateColumns.add(getColumnNamesInSQL(pkNameList));
+                    for (String pkName : pkNameList) {
+                        if (StringUtils.isNotBlank(tableAlias)) {
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: 为什么每次遍历都要判断tableAlias是否为空?
Why do I have to determine if tableAlias is empty for each traversal?

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 2]
```diff
@@ -521,17 +521,22 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
...
+                        } else {
+                            needUpdateColumns.add(getColumnNameInSQL(pkName));
+                        }
                     }
                 }
             }
-            needUpdateColumns.addAll(unescapeColumns.stream()
-                .map(unescapeUpdateColumn -> ColumnUtils.addEscape(unescapeUpdateColumn, getDbType(), tableMeta)).collect(
-                    Collectors.toList()));
+            for (String unescapeColumn : unescapeColumns) {
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: 为什么不使用stream的distinct来去重
Why not use stream's distinct for de-duplication?

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 3]
```diff
@@ -521,17 +521,22 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
...
                 List<String> pkNameList = tableMeta.getEscapePkNameList(getDbType());
+
                 if (CollectionUtils.isNotEmpty(pkNameList)) {
-                    if (StringUtils.isNotBlank(tableAlias)) {
-                        needUpdateColumns.add(getColumnNamesWithTablePrefix(table, tableAlias, pkNameList));
-                    } else {
-                        needUpdateColumns.add(getColumnNamesInSQL(pkNameList));
+                    for (String pkName : pkNameList) {
+                        if (StringUtils.isNotBlank(tableAlias)) {
+                            needUpdateColumns.add(getColumnNameWithTablePrefix(table, tableAlias, pkName));
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: 为什么不直接使用pkNameList入参,而是pkname?
Why don't you just use the pkNameList parameter instead of pkname?

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 1 above)
Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: fixed

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 3 above)
Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: fixed

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 4]
```diff
@@ -247,20 +237,43 @@ protected String getColumnNamesInSQL(List<String> columnNameList) {
...
         return columnNamesStr.toString();
     }
 
+    /**
+     * Gets column name in sql.
+     *
+     * @param columnName the column name
+     * @return the column name in sql
+     */
+    protected String getColumnNameInSQL(String columnName) {
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:254]: 为什么要移动这段代码位置？而不是在它后面增加新方法？
Why move this piece of code instead of adding the new method after it?

Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:254]: because reordering the type of method it looks more beautiful.

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 2 above)
Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: because it has two list, and use for loop let it more readable.

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 4 above)
Comment (funky-eyes) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:254]: > because reordering the type of method it looks more beautiful.

那为什么不是将getColumnNamesInSQLList 挪到上面?
So why not move getColumnNamesInSQLList to the top?

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 2 above)
Comment (funky-eyes) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: Use stream so that the community can readily improve performance by parallelizing streams
使用stream以便社区随时可以通过并行流来提升性能

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 5]
```diff
@@ -523,15 +547,18 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
...
+                        needUpdateColumns.addAll(getColumnNamesInSQLList(pkNameList));
                     }
                 }
             }
-            needUpdateColumns.addAll(unescapeColumns.stream()
-                .map(unescapeUpdateColumn -> ColumnUtils.addEscape(unescapeUpdateColumn, getDbType(), tableMeta)).collect(
-                    Collectors.toList()));
+
+            for (String unescapeColumn : unescapeColumns) {
+                if (!containsColumn(needUpdateColumns, unescapeColumn)) {
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: 每一次调用containsColumn都需要重新构建一个unescape的columns，为什么要这么做？
Each call to containsColumn needs to rebuild an unescape need update column list, why do this?

**Review by funky-eyes — CHANGES_REQUESTED** [review]

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 6]
```diff
@@ -192,18 +192,6 @@ protected String buildLimitCondition(WhereRecognizer recognizer, ArrayList<List<
         return limitCondition;
     }
 
-    /**
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:196]:
```suggestion
    /**
     * Gets column name in sql.
     *
     * @param columnName the column name
     * @return the column name in sql
     */
    protected String getColumnNameInSQL(String columnName) {
        String tableAlias = sqlRecognizer.getTableAlias();
        return tableAlias == null ? columnName : tableAlias + "." + columnName;
    }

    /**
     * Gets column names in sql.
     *
     * @param columnNames the column names
     * @return
     */
    protected List<String> getColumnNamesInSQLList(List<String> columnNames) {
        List<String> columnNameWithTableAlias = new ArrayList<>();
        for (String columnName : columnNames) {
            columnNameWithTableAlias.add(this.getColumnNameInSQL(columnName));
        }
        return columnNameWithTableAlias;
    }
    
```

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 7]
```diff
@@ -247,20 +237,43 @@ protected String getColumnNamesInSQL(List<String> columnNameList) {
...
+    /**
+     * Gets column name in sql.
+     *
+     * @param columnName the column name
+     * @return the column name in sql
+     */
+    protected String getColumnNameInSQL(String columnName) {
+        String tableAlias = sqlRecognizer.getTableAlias();
+        return tableAlias == null ? columnName : tableAlias + "." + columnName;
+    }
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:257]:
```suggestion
```

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 8]
```diff
@@ -247,20 +237,43 @@ protected String getColumnNamesInSQL(List<String> columnNameList) {
...
+     * @return
+     */
+    protected List<String> getColumnNamesInSQLList(List<String> columnNames) {
+        List<String> columnNameWithTableAlias = new ArrayList<>();
+        for (String columnName : columnNames) {
+            columnNameWithTableAlias.add(this.getColumnNameInSQL(columnName));
+        }
+        return columnNameWithTableAlias;
+    }
+
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:272]:
```suggestion
```

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 4 above)
Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java:254]: 3 method of `getColumnNamesWithTablePrefix` and 3 method of `getColumnNameInSQL`. I just put it together

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java (hunk 2 above)
Comment (l81893521) [reply rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]: fixed

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 9]
```diff
@@ -542,18 +559,15 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
                         .collect(Collectors.toList());
             }
             onUpdateColumns.removeAll(unescapeColumns);
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]:
```suggestion
```
已经是treeset了，还需要这一行处理吗？
It's already treeset, do I still need this line of processing?

File: rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java [hunk 10]
```diff
@@ -103,49 +95,149 @@ public static void init() {
...
+
+        TableRecords beforeImage = updateExecutor.beforeImage();
+        TableRecords afterImage = updateExecutor.afterImage(beforeImage);
+        Assertions.assertNotNull(beforeImage);
         Assertions.assertNotNull(afterImage);
+    }
+
+    @Test
+    public void testBeforeAndAfterImageWithKeywordQuote() throws SQLException {
+        String sql = "update table_update_executor_test set `all` = '1234' where id = 1";
```
Comment (funky-eyes) [inline rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java]:
```suggestion
        String sql = "update table_update_executor_test set `all` = '1234', `updated` = `567` where id = 1";
```
Add test ON UPDATE CURRENT_TIMESTAMP for column name test
增加测试ON UPDATE CURRENT_TIMESTAMP的列名测试

File: rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java [hunk 11]
```diff
@@ -103,49 +95,149 @@ public static void init() {
...
         TableRecords beforeImage = updateExecutor.beforeImage();
         TableRecords afterImage = updateExecutor.afterImage(beforeImage);
+        Assertions.assertNotNull(beforeImage);
         Assertions.assertNotNull(afterImage);
+    }
 
-        afterImage = updateExecutor.afterImage(new TableRecords());
+    @Test
+    public void testBeforeAndAfterImageWithTableAliasAndUpperColumn() throws SQLException {
+        String sql = "update table_update_executor_test t set t.NAME = 'WILL' where t.ID = 1";
```
Comment (funky-eyes) [inline rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java]:
```suggestion
        String sql = "update table_update_executor_test t set t.NAME = 'WILL', t.UPDATED = `567` where t.ID = 1";
```
Use case for adding table aliases and capitalizing `ON UPDATE CURRENT_TIMESTAMP` column names
增加表别名与`ON UPDATE CURRENT_TIMESTAMP`列名大写的用例

File: rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java [hunk 12]
```diff
@@ -103,49 +95,149 @@ public static void init() {
...
+        TableRecords afterImage = updateExecutor.afterImage(beforeImage);
         Assertions.assertNotNull(beforeImage);
-        Assertions.assertNotNull(updateExecutor.afterImage(beforeImage));
+        Assertions.assertNotNull(afterImage);
     }
 
     @Test
-    public void testAfterImage() throws SQLException {
+    public void testBeforeAndAfterImageWithUpperColumn() throws SQLException {
+        String sql = "update table_update_executor_test set NAME = 'WILL' where ID = 1";
```
Comment (funky-eyes) [inline rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java]:
```suggestion
        String sql = "update table_update_executor_test set NAME = 'WILL', UPDATED = `567` where ID = 1";
```

File: rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java [hunk 13]
```diff
@@ -542,18 +559,15 @@ protected List<String> getNeedColumns(String table, String tableAlias, List<Stri
...
         } else {
             Stream<String> allColumns = tableMeta.getAllColumns().keySet().stream();
             if (StringUtils.isNotBlank(tableAlias)) {
                 allColumns = allColumns.map(columnName -> getColumnNameWithTablePrefix(table, tableAlias, columnName));
             }
-            allColumns = allColumns.map(columnName -> ColumnUtils.addEscape(columnName, getDbType(), tableMeta));
             allColumns.forEach(needUpdateColumns::add);
         }
-        return needUpdateColumns;
+        return needUpdateColumns.parallelStream().map(column -> ColumnUtils.addEscape(column, getDbType(), tableMeta)).collect(Collectors.toList());
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java]:
```suggestion
        return needUpdateColumns.stream().map(column -> ColumnUtils.addEscape(column, getDbType(), tableMeta)).collect(Collectors.toList());
```
With stream, when there are not many columns involved, stream is theoretically better.

**Review by funky-eyes — APPROVED** [review]
LGTM
