### PR TITLE
bugfix: fix incorrect metric report

### LINKED ISSUE #6016: Duplicate commit event publishing causes incorrect transaction metric
- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

There is a **committed event publishing** in ll.169 of `DefaultCore#commit`.

https://github.com/seata/seata/blob/8192138895ada3cc7cd09977f3219ed8371c17ae/server/src/main/java/io/seata/server/coordinator/DefaultCore.java#L169

However, there is another **committed event publishing** in ll.150 of `SessionHelper#endCommitted`,

https://github.com/seata/seata/blob/8192138895ada3cc7cd09977f3219ed8371c17ae/server/src/main/java/io/seata/server/session/SessionHelper.java#L140-L161

which leads to calling `MetricsSubscriber#processGlobalStatusCommitted` twice, i.e., a double deduction on the `active` metric and a double increasement on the `committed` metric.

image

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by ptyin**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

Fix incorrect metric report. 

It's actually a accidental code error. The conditions in

https://github.com/seata/seata/blob/8192138895ada3cc7cd09977f3219ed8371c17ae/server/src/main/java/io/seata/server/session/SessionHelper.java#L149

and in

https://github.com/seata/seata/blob/8192138895ada3cc7cd09977f3219ed8371c17ae/server/src/main/java/io/seata/server/session/SessionHelper.java#L221

intend to distinguish whether `retryGlobal` is true or false. Therefore, `retryGlobal` should be evaluated instead of `DELAY_HANDLE_SESSION`.

### Ⅱ. Does this pull request fix one issue?

fixes #6016

### CODE REVIEW

File: server/src/main/java/io/seata/server/session/SessionHelper.java [hunk 1]
```diff
@@ -146,7 +146,7 @@ public static void endCommitted(GlobalSession globalSession, boolean retryGlobal
                 globalSession.changeGlobalStatus(GlobalStatus.Committed);
             }
             globalSession.end();
-            if (!DELAY_HANDLE_SESSION) {
```
Comment (funky-eyes) [inline server/src/main/java/io/seata/server/session/SessionHelper.java:149]: file和raft模式时,外层的if是不成立的,所以需要在这里打end的点和after的点,而其它模式在二阶段决议时是走的else逻辑,committed已经在二阶段决议时完成了,所以在这不需要再打点
file and raft mode, the outer if is not established, so you need to hit the end of the point here and after the point, while the other modes in the two-stage resolution is to go to the else logic, committed has been completed in the two-stage resolution, so no need to hit the point here!

Comment (ptyin) [reply server/src/main/java/io/seata/server/session/SessionHelper.java:149]: Got it. Leave this line unchanged, and modify the `MetricsPublisher.postSessionDoneEvent(globalSession, false, false);` to `MetricsPublisher.postSessionDoneEvent(globalSession, retryGlobal, false);` in the inner block. I think that makes more sense.

**Review by funky-eyes — APPROVED** [review]
LGTM
