### PR TITLE
optimize: remove p3c, use maven-checkstyle-plugin, only check PR changes.

### LINKED ISSUE #8056: P3C appears to be abandoned — no updates since 2022
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [x] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

_No response_

### Ⅱ. Describe what happened

_No response_

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

_No response_

### PR DESCRIPTION
**Pull request by xuxiaowei-com-cn**
- [x] I have read the [CONTRIBUTING.md](https://github.com/apache/incubator-seata/blob/2.x/CONTRIBUTING.md) guidelines.
- [x] I have registered the PR [changes](https://github.com/apache/incubator-seata/tree/2.x/changes).

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/apache/incubator-seata/issues/8056

### CODE REVIEW

**Review by funky-eyes — COMMENTED** [review]
I would still prefer to keep PMD or find an alternative to P3C. Otherwise, it will be difficult to enforce standards for variable naming conventions, code style, enum comments, and code annotations. At the very least, it currently provides some level of constraint on the JDK 8 pipeline, helping to maintain standardization.

**Comment by xuxiaowei-com-cn** [comment]
> I would still prefer to keep PMD or find an alternative to P3C. Otherwise, it will be difficult to enforce standards for variable naming conventions, code style, enum comments, and code annotations. At the very least, it currently provides some level of constraint on the JDK 8 pipeline, helping to maintain standardization.

# 中文

1. 我看到项目中引入了 `org.apache.maven.plugins:maven-checkstyle-plugin`，并且被禁用了。
2. `org.apache.maven.plugins:maven-checkstyle-plugin` 也能实现你说的效果吧？
3. 这个项目已经捐献给 Apache 基金会，使用 `org.apache.maven.plugins:maven-checkstyle-plugin` 也是理所因该的吧？

# English

1. I noticed that the project introduced `org.apache.maven.plugins:maven-checkstyle-plugin`, and it is disabled.  
2. `org.apache.maven.plugins:maven-checkstyle-plugin` can also achieve the effect you mentioned, right?  
3. This project has been donated to the Apache Foundation, so it is only natural to use `org.apache.maven.plugins:maven-checkstyle-plugin`, right?

**Comment by funky-eyes** [comment]
> > I would still prefer to keep PMD or find an alternative to P3C. Otherwise, it will be difficult to enforce standards for variable naming conventions, code style, enum comments, and code annotations. At the very least, it currently provides some level of constraint on the JDK 8 pipeline, helping to maintain standardization.
> 
> # 中文
> 1. 我看到项目中引入了 `org.apache.maven.plugins:maven-checkstyle-plugin`，并且被禁用了。
> 2. `org.apache.maven.plugins:maven-checkstyle-plugin` 也能实现你说的效果吧？
> 3. 这个项目已经捐献给 Apache 基金会，使用 `org.apache.maven.plugins:maven-checkstyle-plugin` 也是理所因该的吧？
> 
> # English
> 1. I noticed that the project introduced `org.apache.maven.plugins:maven-checkstyle-plugin`, and it is disabled.
> 2. `org.apache.maven.plugins:maven-checkstyle-plugin` can also achieve the effect you mentioned, right?
> 3. This project has been donated to the Apache Foundation, so it is only natural to use `org.apache.maven.plugins:maven-checkstyle-plugin`, right?

If the maven-checkstyle-plugin can replace the capabilities of PMD, I agree with your suggestion.

**Comment by xuxiaowei-com-cn** [comment]
> > > I would still prefer to keep PMD or find an alternative to P3C. Otherwise, it will be difficult to enforce standards for variable naming conventions, code style, enum comments, and code annotations. At the very least, it currently provides some level of constraint on the JDK 8 pipeline, helping to maintain standardization.
> > 
> > 
> > # 中文
> > 
> > 1. 我看到项目中引入了 `org.apache.maven.plugins:maven-checkstyle-plugin`，并且被禁用了。
> > 2. `org.apache.maven.plugins:maven-checkstyle-plugin` 也能实现你说的效果吧？
> > 3. 这个项目已经捐献给 Apache 基金会，使用 `org.apache.maven.plugins:maven-checkstyle-plugin` 也是理所因该的吧？
> > 
> > # English
> > 
> > 1. I noticed that the project introduced `org.apache.maven.plugins:maven-checkstyle-plugin`, and it is disabled.
> > 2. `org.apache.maven.plugins:maven-checkstyle-plugin` can also achieve the effect you mentioned, right?
> > 3. This project has been donated to the Apache Foundation, so it is only natural to use `org.apache.maven.plugins:maven-checkstyle-plugin`, right?
> 
> If the maven-checkstyle-plugin can replace the capabilities of PMD, I agree with your suggestion.

- 需要研究一下 p3c 的规则与 `org.apache.maven.plugins:maven-checkstyle-plugin` 的规则，并将规则进行转换。
- It is necessary to study the rules of p3c and those of `org.apache.maven.plugins:maven-checkstyle-plugin`, and then convert the rules.

**Comment by xuxiaowei-com-cn** [comment]
@funky-eyes 

- 已使用 maven-checkstyle-plugin 替换 p3c。
- Replaced p3c with maven-checkstyle-plugin.

File: saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java [hunk 1]
```diff
@@ -117,8 +117,6 @@ public static void setMachineStatusBasedOnStateListAndException(
                             hasSuccessUpdateService = true;
                         }
                     }
-                } else if (ExecutionStatus.SK.equals(stateInstance.getStatus())) {
```
Comment (funky-eyes) [inline saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java:120]: Removing this code would break the logic, right?

File: server/src/main/java/org/apache/seata/server/storage/file/lock/FileLocker.java [hunk 2]
```diff
@@ -95,8 +95,6 @@ public boolean acquireLock(List<RowLock> rowLocks, boolean autoCommit, boolean s
                 Set<String> keysInHolder = CollectionUtils.computeIfAbsent(
                         bucketHolder, bucketLockMap, key -> ConcurrentHashMap.newKeySet());
                 keysInHolder.add(pk);
-            } else if (previousLockBranchSession.getTransactionId() == transactionId) {
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/storage/file/lock/FileLocker.java:98]: Removing this code would break the logic, right?

File: saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java (hunk 1 above)
Comment (xuxiaowei-com-cn) [reply saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java:120]: # English

1. This is because the `<module name="EmptyBlock"/>` is enabled in `style/checkstyle.xml`.  
2. I think it would be unreasonable to simply remove the `<module name="EmptyBlock"/>` rule.  
3. If you need to keep that empty line of code, you can enable `<module name="SuppressWarningsHolder"/>` and use `@SuppressWarnings("checkstyle:EmptyBlock")` to suppress that specific check.  
4. Note: Using `@SuppressWarnings("checkstyle:...")` may lead to abuse.

# 中文

1. 这个原因是因为在 `style/checkstyle.xml` 启用了 `<module name="EmptyBlock"/>`
2. 我觉得如果要删除 `<module name="EmptyBlock"/>` 规则是不合理的
3. 如果需要保留这行空代码，可以启用 `<module name="SuppressWarningsHolder"/>`，并使用 `@SuppressWarnings("checkstyle:EmptyBlock")` 忽略某个检查。
4. 注意：使用 `@SuppressWarnings("checkstyle:...")` 可能会出现滥用的情况。

File: server/src/main/java/org/apache/seata/server/storage/file/lock/FileLocker.java (hunk 2 above)
Comment (xuxiaowei-com-cn) [reply server/src/main/java/org/apache/seata/server/storage/file/lock/FileLocker.java:98]: # English

1. This is because the `<module name="EmptyBlock"/>` is enabled in `style/checkstyle.xml`.  
2. I think it would be unreasonable to simply remove the `<module name="EmptyBlock"/>` rule.  
3. If you need to keep that empty line of code, you can enable `<module name="SuppressWarningsHolder"/>` and use `@SuppressWarnings("checkstyle:EmptyBlock")` to suppress that specific check.  
4. Note: Using `@SuppressWarnings("checkstyle:...")` may lead to abuse.

# 中文

1. 这个原因是因为在 `style/checkstyle.xml` 启用了 `<module name="EmptyBlock"/>`
2. 我觉得如果要删除 `<module name="EmptyBlock"/>` 规则是不合理的
3. 如果需要保留这行空代码，可以启用 `<module name="SuppressWarningsHolder"/>`，并使用 `@SuppressWarnings("checkstyle:EmptyBlock")` 忽略某个检查。
4. 注意：使用 `@SuppressWarnings("checkstyle:...")` 可能会出现滥用的情况。

Comment (xuxiaowei-com-cn) [reply server/src/main/java/org/apache/seata/server/storage/file/lock/FileLocker.java:98]: - 代码已经撤回。
- maven-checkstyle-plugin 仅检查 PR 变更。
- The code has been reverted.  
- The maven-checkstyle-plugin only checks PR changes.

File: saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java (hunk 1 above)
Comment (xuxiaowei-com-cn) [reply saga/seata-saga-engine/src/main/java/org/apache/seata/saga/engine/strategy/impl/DefaultStatusDecisionStrategy.java:120]: - 代码已经撤回。
- maven-checkstyle-plugin 仅检查 PR 变更。
- The code has been reverted.  
- The maven-checkstyle-plugin only checks PR changes.

**Review by funky-eyes — APPROVED** [review]
LGTM
