### PR TITLE
optimize: Druid SQL parser throws ParserException for unsupported REPLACE statement

### LINKED ISSUE #7452: Druid SQL parser throws ParserException for unsupported `REPLACE` statement
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

While running the `DruidSQLRecognizerFactoryTest.testIsSqlSyntaxSupports` test, a `ParserException` is thrown when attempting to parse a SQL statement that starts with `REPLACE`. This indicates that the Druid SQL parser does not support the `REPLACE` SQL syntax.

### Ⅱ. Describe what happened

Stack Trace:

```
com.alibaba.druid.sql.parser.ParserException: not supported.pos 7, line 1, column 1, token REPLACE
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:616)
	at com.alibaba.druid.sql.SQLUtils.parseStatements(SQLUtils.java:603)
	at org.apache.seata.sqlparser.druid.DruidSQLRecognizerFactoryImpl.create(DruidSQLRecognizerFactoryImpl.java:41)
	at org.apache.seata.sqlparser.druid.DruidSQLRecognizerFactoryTest.testIsSqlSyntaxSupports(DruidSQLRecognizerFactoryTest.java:172)
```

- https://github.com/apache/incubator-seata/actions/runs/15748629211/job/44389506909?pr=7450

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

Environment:

- Module: sqlparser-druid
- Test class: DruidSQLRecognizerFactoryTest
- SQL: REPLACE INTO ...

### PR DESCRIPTION
**Pull request by maple525866**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
1.Modify DruidSQLRecognizerFactoryImpl (unify exception types)
   a.I refactored the implementation classes so that they all throw exceptions uniformly

   b.At the same time, in order to prevent direct reference to ParserException and cause class loading dependency problems, the exception is handled by reflection.

2.Modify DruidSQLRecognizerFactoryTest and retest

### Ⅱ. Does this pull request fix one issue?

fixes #7452

### CODE REVIEW

File: sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java [hunk 1]
```diff
@@ -38,42 +38,47 @@
...
-            if (ast instanceof SQLInsertStatement) {
-                recognizer = recognizerHolder.getInsertRecognizer(sql, ast);
-            } else if (ast instanceof SQLUpdateStatement) {
-                recognizer = recognizerHolder.getUpdateRecognizer(sql, ast);
-            } else if (ast instanceof SQLDeleteStatement) {
-                recognizer = recognizerHolder.getDeleteRecognizer(sql, ast);
-            } else if (ast instanceof SQLSelectStatement) {
-                recognizer = recognizerHolder.getSelectForUpdateRecognizer(sql, ast);
+        try {
+            List<SQLStatement> asts = SQLUtils.parseStatements(sql, DruidDbTypeAdapter.getAdaptiveDbType(dbType));
```
Comment (WangzJi) [inline sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java]: Looks good! Just a suggestion — perhaps we could replace `asts` with something more descriptive like `sqlStatements` or `parsedStatements` for better readability. Avoiding abbreviations in variable names can help with clarity in the long run. What do you think?

Comment (maple525866) [reply sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java]: Of course, I will check its specific functions later and give it a suitable name 。 @YongGoose Do you have any suggestions for suitable names?

Comment (maple525866) [reply sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java]: If I had to choose, I would choose sqlStatements as the new name

File: sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java [hunk 2]
```diff
@@ -38,43 +38,65 @@
...
-                    SQLOperateRecognizerHolderFactory.getSQLRecognizerHolder(dbType.toLowerCase());
-            if (ast instanceof SQLInsertStatement) {
-                recognizer = recognizerHolder.getInsertRecognizer(sql, ast);
-            } else if (ast instanceof SQLUpdateStatement) {
-                recognizer = recognizerHolder.getUpdateRecognizer(sql, ast);
-            } else if (ast instanceof SQLDeleteStatement) {
-                recognizer = recognizerHolder.getDeleteRecognizer(sql, ast);
-            } else if (ast instanceof SQLSelectStatement) {
-                recognizer = recognizerHolder.getSelectForUpdateRecognizer(sql, ast);
+        try {
```
Comment (YongGoose) [inline sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java:42]: Was there a specific reason you added the try block?

**Review by YongGoose — COMMENTED** [review]
Based on the error log, it seems the issue occurred because the `REPLACE` statement isn’t supported.

May I ask how you handled or worked around this in your current changes?

File: sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java (hunk 1 above)
Comment (YongGoose) [reply sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java]: I also think `sqlStatements` is a good choice.

**Comment by maple525866** [comment]
> 根据错误日志，问题似乎是因为该`REPLACE`语句不受支持而发生的。
> 
> 我可以问一下您在当前的更改中如何处理或解决这个问题吗？

The main problem we need to solve is that the REPLACE statement in the test class is not supported and throws a ParserException, which causes a Maven build error.

My solution:
Modify DruidSQLRecognizerFactoryImpl.java and convert Druid's ParserException to Seata's NotSupportYetException.

At the same time, in order to take into account the previous test class, use reflection to check the exception type and avoid directly referencing ParserException

Result:
GitHub Action builds successfully
Unified exception handling - all unsupported SQL syntax throws NotSupportYetException
Consistent test logic - all database types use the same test assertions
Compatibility is maintained - other tests such as DruidIsolationTest run normally

File: sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java (hunk 2 above)
Comment (maple525866) [reply sqlparser/seata-sqlparser-druid/src/main/java/org/apache/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java:42]: Catch the exception through try-catch, and decide whether to convert it into NotSupportYetException

**Comment by YongGoose** [comment]
> The main problem we need to solve is that the REPLACE statement in the test class is not supported and throws a ParserException, which causes a Maven build error.
> 
> My solution: Modify DruidSQLRecognizerFactoryImpl.java and convert Druid's ParserException to Seata's NotSupportYetException.
> 
> At the same time, in order to take into account the previous test class, use reflection to check the exception type and avoid directly referencing ParserException
> 
> Result: GitHub Action builds successfully Unified exception handling - all unsupported SQL syntax throws NotSupportYetException Consistent test logic - all database types use the same test assertions Compatibility is maintained - other tests such as DruidIsolationTest run normally

I hadn’t looked closely at the test code 😅, changing it to `NotSupportYetException` does seem effective!

I think the current approach is fine as well, but how about wrapping only the methods that throw ParserException in a try-catch block?
- Currently, the entire method is wrapped in a try-catch block, which I think hurts readability.

**Comment by maple525866** [comment]
> > 我们需要解决的主要问题是测试类中的 REPLACE 语句不受支持，并抛出 ParserException，从而导致 Maven 构建错误。
> > 我的解决方案：修改DruidSQLRecognizerFactoryImpl.java，将Druid的ParserException转换为Seata的NotSupportYetException。
> > 同时，为了兼顾之前的测试类，使用反射来检查异常类型，避免直接引用ParserException
> > 结果：GitHub Action 构建成功；统一异常处理 - 所有不支持的 SQL 语法都会抛出 NotSupportYetException；一致的测试逻辑 - 所有数据库类型都使用相同的测试断言；保持兼容性 - 其他测试（如 DruidIsolationTest）正常运行
> 
> 我没有仔细看测试代码😅，将其更改为`NotSupportYetException`确实看起来有效！
> 
> 我认为当前的方法也很好，但是如何仅将抛出 ParserException 的方法包装在 try-catch 块中？
> 
> * 目前，整个方法都包裹在 try-catch 块中，我认为这会影响可读性。

done

**Review by YongGoose — APPROVED** [review]
LGTM

**Comment by YongGoose** [comment]
@funky-eyes 

PTAL

**Comment by maple525866** [comment]
PTAL
@funky-eyes

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
If you're using the DingTalk app, please send your DingTalk account to my email at jianbin@apache.org, and I will invite you to join the Seata developer group
