### PR TITLE
test : fix mockserverTest fail cause using same port with seata-server 

### LINKED ISSUE #6320: MockServerTest.testRollback  UT failed
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

image
https://github.com/apache/incubator-seata/actions/runs/7750961970/job/21138032865?pr=6254

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by Bughue**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
mockserverTest fail cause using same port with seata-server 

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/apache/incubator-seata/issues/6320

### CODE REVIEW

File: core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingServer.java [hunk 1]
```diff
@@ -268,4 +268,8 @@ public void close(ChannelHandlerContext ctx, ChannelPromise future) throws Excep
         }
 
     }
+
+    protected void setListenPort(int listenPort){
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingServer.java]: 为什么不使用system.setproperty("SEATA_PORT")，或者properties配置等方式指定端口，而是开放setListenPort？
Why not specify the port using system.setproperty("SEATA_PORT"), or properties configuration, etc., but instead open up setListenPort?

Comment (Bughue) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingServer.java]: > 为什么不使用system.setproperty("SEATA_PORT")，或者properties配置等方式指定端口，而是开放setListenPort？ Why not specify the port using system.setproperty("SEATA_PORT"), or properties configuration, etc., but instead open up setListenPort?

为了方便给测试类直接代码决定port值，而且在测试里同时有mock-server和普通server的情况下，共用那个配置也分不清
To make it easier to determine the port value for the test class, and in the case of having both a mock-server and a regular server in the test, it's hard to tell if it's sharing that configuration.

**Comment by xingfudeshi** [comment]
Please register this PR in changes

File: core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingServer.java (hunk 1 above)
Comment (funky-eyes) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingServer.java]: > > 为什么不使用system.setproperty("SEATA_PORT")，或者properties配置等方式指定端口，而是开放setListenPort？ Why not specify the port using system.setproperty("SEATA_PORT"), or properties configuration, etc., but instead open up setListenPort?
> 
> 为了方便给测试类直接代码决定port值，而且在测试里同时有mock-server和普通server的情况下，共用那个配置也分不清 To make it easier to determine the port value for the test class, and in the case of having both a mock-server and a regular server in the test, it's hard to tell if it's sharing that configuration.

有mock-server的时候在启动前往system.setproperty就行了，不存在共用配置的问题，-D参数优先级是最高的，或者seata.server.service-port这个key
There are mock-server in the startup to system.setproperty on the line, there is no problem of shared configuration, -D parameter priority is the highest, or seata.server.service-port the key

File: test/src/test/java/org/apache/seata/core/rpc/netty/mockserver/MockServerTest.java [hunk 2]
```diff
@@ -32,42 +32,44 @@ public class MockServerTest {
...
+
     @BeforeAll
     public static void before() {
         MockServer.start();
     }
 
-    @AfterAll
+//    @AfterAll
     public static void after() {
         MockServer.close();
```
Comment (funky-eyes) [inline test/src/test/java/org/apache/seata/core/rpc/netty/mockserver/MockServerTest.java:48]: why not close?

File: test/src/test/java/org/apache/seata/core/rpc/netty/mockserver/MockServerTest.java [hunk 3]
```diff
@@ -91,7 +93,7 @@ private static String doTestRollback(int times) throws TransactionException {
         MockCoordinator.getInstance().setExpectedRetry(xid, times);
         Long branchId = rm.branchRegister(BranchType.AT, RESOURCE_ID, "1", xid, "1", "1");
         GlobalStatus rollback = tm.rollback(xid);
-        Assertions.assertEquals(rollback, GlobalStatus.Rollbacked);
+        Assertions.assertTrue(rollback == GlobalStatus.Rollbacked || rollback == GlobalStatus.Finished);
```
Comment (funky-eyes) [inline test/src/test/java/org/apache/seata/core/rpc/netty/mockserver/MockServerTest.java]: why status is Finished?

File: test-mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java [hunk 4]
```diff
@@ -52,24 +54,33 @@ public static void main(String[] args) {
...
+                    inited = true;
+                    workingThreads = new ThreadPoolExecutor(50,
+                            50, 500, TimeUnit.SECONDS,
+                            new LinkedBlockingQueue<>(20000),
+                            new NamedThreadFactory("ServerHandlerThread", 500), new ThreadPoolExecutor.CallerRunsPolicy());
+                    nettyRemotingServer = new MockNettyRemotingServer(workingThreads, 8099);
+
+                    // set registry
+                    XID.setIpAddress(NetUtil.getLocalIp());
+                    XID.setPort(8099);
```
Comment (slievrly) [inline test-mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java]: ports should be customized, not fixed.

File: test-mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java [hunk 5]
```diff
@@ -50,23 +55,28 @@ public class MockServer {
...
     }
 
-    public static void start() {
+    public static void start(int port) {
         if (!inited) {
             synchronized (MockServer.class) {
                 if (!inited) {
                     inited = true;
+                    System.setProperty(ConfigurationKeys.SERVER_SERVICE_PORT_CAMEL, String.valueOf(port));
+                    ConfigurationCache.getInstance().onChangeEvent(new ConfigurationChangeEvent(ConfigurationKeys.SERVER_SERVICE_PORT_CAMEL, String.valueOf(port)));
```
Comment (slievrly) [inline test-mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java]: I don't think this is a user API.

File: test-mock-server/pom.xml [hunk 6]
```diff
@@ -40,7 +40,7 @@
         </plugins>
     </build>
 
-    <dependencies>
+        <dependencies>
         <dependency>
```
Comment (funky-eyes) [inline test-mock-server/pom.xml]:
```suggestion
    <dependencies>
        <dependency>
```

File: test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+
+
+    private static final long PUT_CONFIG_TIMEOUT = 30000L;
+    private static final long PUT_CONFIG_CHECK_GAP = 500L;
+
+    public static void removeConfig(String dataId) {
+        putConfig(dataId, null);
+    }
+
+    public static void putConfig(String dataId, String content) {
```
Comment (slievrly) [inline test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java:39]: You want to understand what the purpose of mock-server is? Connecting to the Seata-Server as if using a normal SDK eliminates the cumbersome Seata-Server setup, which is useful for testing client integration. If the user gets this mock-server, need to write such complex logic to test it, what is the point of it?

Comment (Bughue) [reply test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java:39]: I understand the point of mock-server, this class is only used for tests where you need to dynamically change the configuration in the unit test. It is only involved in the mock-server unit tests because it shares a key with TC-server.
Normal users don't need to use this test class to use mock-server, if they want to change the port they just need to use mock-server/resource/application.yml
This complexity arises because the unit tests for both mock-server and seata-server are in one package, or maybe we can create another test subproject for mock-server?

我理解mock-server的意义，这个类仅用于测试时需要动态改变单元测试里的配置。在mock-server的单元测试里因为和TC-server共用了一个key才会涉及它。
正常的用户在使用mock-server里是不需要用到这个test类的，他们如果想改变端口只需要使用mock-server/resource/application.yml
这个复杂性的出现是因为mock-server和seata-server的单元测试都在一个包里，又或者我们可以为mock-server再建一个test子项目？

File: test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+            System.clearProperty(dataId);
+            ConfigurationFactory.getInstance().removeConfig(dataId);
+            return;
+        }
+
+        System.setProperty(dataId, content);
+        ConfigurationFactory.getInstance().putConfig(dataId, content);
+
+        long start = System.currentTimeMillis();
+        while (!ObjectUtils.equals(content, ConfigurationFactory.getInstance().getConfig(dataId))) {
```
Comment (funky-eyes) [inline test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java]: 为什么不用CountDownLatch?
Why not use CountDownLatch?

Comment (Bughue) [reply test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java]: 这里的等待是等缓存刷新，不是并发次数控制，所以用CountDownLatch没用吧

Comment (funky-eyes) [reply test/src/test/java/org/apache/seata/common/ConfigurationTestHelper.java]: > 这里的等待是等缓存刷新，不是并发次数控制，所以用CountDownLatch没用吧

你建立了一个listener，CountDownLatch的countDown动作放在listener实现里，外面这个地方进行等待，就不需要while了。
You create a listener, the CountDownLatch's countDown action is placed in the listener implementation, and this place outside does the waiting, eliminating the need for while.

**Review by funky-eyes — APPROVED** [review]
LGTM

**Review by slievrly — APPROVED** [review]
OK. However, I hope that the xid port and listen port can be set uniformly in the future.
