### PR TITLE
bugfix: fix deserialization failure when the XSS filter retrieved the default keyword

### LINKED ISSUE #7595: 'server.http.filter.xss.keywords'. Expected a JSON array like ["<script>", "vbscript:"], but got: [<script>, </script>, javascript:, vbscript:
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [ ] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

server在因为 'server.http.filter.xss.keywords'报错

### Ⅱ. Describe what happened

'server.http.filter.xss.keywords' configuration error, you need to fix the default configuration or change the configuration resolution method
```
org.apache.seata.common.loader.EnhancedServiceNotFoundException: java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@499421a6, class: interface org.apache.seata.core.rpc.netty.http.filter.HttpRequestFilter)  could not be instantiated: Invalid format for configuration 'server.http.filter.xss.keywords'. Expected a JSON array like ["<script>", "vbscript:"], but got: [<script>, </script>, javascript:, vbscript:, data:, expression(, onerror, onload, onclick, onmouseover, onfocus, onblur, onmouseenter, onmouseleave, onkeydown, onkeyup, onchange, <iframe>, <img>, <svg>, <embed>, <object>, <style>, <link>]
Caused by: java.lang.IllegalStateException: Extension instance(definition: org.apache.seata.common.loader.ExtensionDefinition@499421a6, class: interface org.apache.seata.core.rpc.netty.http.filter.HttpRequestFilter)  could not be instantiated: Invalid format for configuration 'server.http.filter.xss.keywords'. Expected a JSON array like ["<script>", "vbscript:"], but got: [<script>, </script>, javascript:, vbscript:, data:, expression(, onerror, onload, onclick, onmouseover, onfocus, onblur, onmouseenter, onmouseleave, onkeydown, onkeyup, onchange, <iframe>, <img>, <svg>, <embed>, <object>, <style>, <link>]
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:496)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:477)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:412)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:393)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$500(EnhancedServiceLoader.java:277)
	at org.apache.seata.common.loader.EnhancedServiceLoader.loadAll(EnhancedServiceLoader.java:175)
	at org.apache.seata.core.rpc.netty.http.filter.HttpRequestFilterManager.initializeFilters(HttpRequestFilterManager.java:41)
	at org.apache.seata.server.spring.listener.HttpFilterInitListener.onApplicationEvent(HttpFilterInitListener.java:30)
	at org.apache.seata.server.spring.listener.HttpFilterInitListener.onApplicationEvent(HttpFilterInitListener.java:23)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:430)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:387)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:952)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at org.apache.seata.server.ServerApplication.main(ServerApplication.java:30)
Caused by: java.lang.IllegalArgumentException: Invalid format for configuration 'server.http.filter.xss.keywords'. Expected a JSON array like ["<script>", "vbscript:"], but got: [<script>, </script>, javascript:, vbscript:, data:, expression(, onerror, onload, onclick, onmouseover, onfocus, onblur, onmouseenter, onmouseleave, onkeydown, onkeyup, onchange, <iframe>, <img>, <svg>, <embed>, <object>, <style>, <link>]
	at org.apache.seata.server.filter.XSSHttpRequestFilter.<init>(XSSHttpRequestFilter.java:72)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:721)
	at org.apache.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:492)
	... 21 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"[<script>, </script>, javascript:, vbscript:, data:, expression(, onerror, onload, onclick, onmouseover, onfocus, onblur, onmouseenter, onmouseleave, onkeydown, onkeyup, onchange, <iframe>, <img>, <svg>, <embed>, <object>, <style>, <link>]"; line: 1, column: 3] (through reference chain: java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:221)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:182)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612)
	at org.apache.seata.server.filter.XSSHttpRequestFilter.<init>(XSSHttpRequestFilter.java:70)
	... 28 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"[<script>, </script>, javascript:, vbscript:, data:, expression(, onerror, onload, onclick, onmouseover, onfocus, onblur, onmouseenter, onmouseleave, onkeydown, onkeyup, onchange, <iframe>, <img>, <svg>, <embed>, <object>, <style>, <link>]"; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:735)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:659)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2005)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:802)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextTextValue(ReaderBasedJsonParser.java:1218)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:201)
	... 35 common frames omitted
 <==

```

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

start server

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

_No response_

### PR DESCRIPTION
**Pull request by YvCeung**
- [x] I have read the [CONTRIBUTING.md](https://github.com/apache/incubator-seata/blob/2.x/CONTRIBUTING.md) guidelines.
- [x] I have registered the PR [changes](https://github.com/apache/incubator-seata/tree/2.x/changes).

### Ⅰ. Describe what this PR did
1. When `xsskeyword` is not explicitly specified, the default configuration will be used. Previously, the default configuration was a collection, which was converted by `String.valueOf()` when retrieved through the configuration class, causing deserialization to fail. This change modifies the default format from a `List<String>` to a `String`, so that when the project starts and retrieves the default configuration, deserialization will no longer fail.

2. **Modify the logic for obtaining keywords through XSSFilter: Previously, it was entirely specified by the user. If the user's configuration was incorrect or the configuration was overwritten, it might lead to the failure of security protection. After optimization, it ensures that the default xss keywords of the system are consistently effective, and at the same time, the user configuration is retained, but it is merged into the total xss keyword set in an appending manner only**

### Ⅱ. Does this pull request fix one issue?

fix #7595 

### Ⅳ. Describe how to verify it
When the configuration file does not specify the `xssKeyWord` property, starting the service without any errors indicates that there is no issue.

### CODE REVIEW

File: server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java [hunk 1]
```diff
@@ -60,21 +59,17 @@ public class XSSHttpRequestFilter implements HttpRequestFilter {
...
-            try {
-                xssKeywords = objectMapper.readValue(xssKeywordConfig, new TypeReference<List<String>>() {});
-            } catch (JsonProcessingException e) {
-                throw new IllegalArgumentException(
-                        "Invalid format for configuration 'server.http.filter.xss.keywords'. "
-                                + "Expected a JSON array like [\"<script>\", \"vbscript:\"], but got: "
-                                + xssKeywordConfig,
-                        e);
-            }
+        String xssKeywordConfig = CONFIG.getConfig(SERVER_HTTP_FILTER_XSS_FILTER_KEYWORDS, DEFAULT_XSS_KEYWORDS);
```
Comment (slievrly) [inline server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: Under what circumstances need to specify the configuration, what do not need to configure?

Comment (slievrly) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: Security is not an option.

Comment (YvCeung) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: > Under what circumstances need to specify the configuration, what do not need to configure?

This is a default configuration. When no specific keywords are specified in the configuration file, these default configuration values will be obtained

Comment (YvCeung) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: > Security is not an option.

The system itself reserves a switch for whether xssFilter is enabled or not. If xss protection is enabled but no specific keywords for protection are specified, the default keywords will be used

Comment (slievrly) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: Why do we need user configuration? Do users need to learn such details? If users configure wrongly, does it mean we can't provide secure services? Security is not an option. At all times, the services we provide must be secure.

Comment (YvCeung) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: > Why do we need user configuration? Do users need to learn such details? If users configure wrongly, does it mean we can't provide secure services? Security is not an option. At all times, the services we provide must be secure.

Ultimately, this comes down to a trade-off between prioritizing security and prioritizing flexible configuration. I believe it should be evaluated on a case-by-case basis. For example, when it comes to XSS protection, it’s impossible to anticipate every potential attack pattern. In such cases, allowing users to update configurations themselves enables a quick response to emerging threats. However, some scenarios must always prioritize security, such as enforcing HTTPS. Users should not be allowed to disable HTTPS for convenience, as doing so could expose all traffic to man-in-the-middle attacks. In situations like this, security measures should be enforced by default rather than left as a configurable option.😀

Comment (slievrly) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: Security has to be the top priority, features come second. If a feature doesn’t meet security standards, it shouldn’t be shipped. We need to ensure safety in all known scenarios — security shouldn’t fail just because users misconfigure something or skip settings. Giving users optional security configurations is a bad idea; that choice shouldn’t be theirs. Thinking about existing web servers: which ones actually follow this rule? If they do, does that mean any security issues caused by user configurations become the user’s fault, and the project avoids getting blamed for CVEs?

Comment (slievrly) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: Even if we were to allow user configuration of these rules as a last resort, the configuration must follow an append-only approach.  Users should only be able to add their own rules on top of the built-in ones, not replace them.  Allowing replacements would risk misconfigurations and security vulnerabilities.

Comment (YvCeung) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: > Even if we were to allow user configuration of these rules as a last resort, the configuration must follow an append-only approach. Users should only be able to add their own rules on top of the built-in ones, not replace them. Allowing replacements would risk misconfigurations and security vulnerabilities.

I think this is a good idea to satisfy both security and user-customised configuration. Next, I will complete the implementation of this idea in this pr.😊

Comment (YvCeung) [reply server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java]: tag: `3f85505` has completed this task

**Comment by YvCeung** [comment]
@slievrly  PTAL

File: server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java [hunk 2]
```diff
@@ -59,11 +65,26 @@ public class XSSHttpRequestFilter implements HttpRequestFilter {
             Pattern.CASE_INSENSITIVE);
 
     public XSSHttpRequestFilter() {
-        String xssKeywordConfig = CONFIG.getConfig(SERVER_HTTP_FILTER_XSS_FILTER_KEYWORDS, DEFAULT_XSS_KEYWORDS);
+        String xssKeywordConfig = CONFIG.getConfig(SERVER_HTTP_FILTER_XSS_FILTER_KEYWORDS, null);
+
+        if (StringUtils.isBlank(xssKeywordConfig)) {
```
Comment (slievrly) [inline server/src/main/java/org/apache/seata/server/filter/XSSHttpRequestFilter.java:69]: If the user does not configure SERVER_HTTP_FILTER_XSS_FILTER_KEYWORDS, then do not enable XSSHttpRequestFilter?

**Comment by YvCeung** [comment]
tag `d2ca733` : Remove the global switch configuration of the filter and the switch configuration of the xss filter, and change it to forced on. The xssFilter only provides users with the ability to add keyword configurations
取消过滤器全局的开关配置以及xss过滤器的开关配置，变更为强制开启，xssFilter仅提供给用户追加风险关键字配置的能力

**Review by slievrly — COMMENTED** [review]
Pls review these files:
https://github.com/apache/incubator-seata/blob/2.x/script/config-center/config.txt#L209
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.example.yml#L181
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.raft.example.yml#L157

**Comment by YvCeung** [comment]
> Pls review these files: https://github.com/apache/incubator-seata/blob/2.x/script/config-center/config.txt#L209 https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.example.yml#L181 https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.raft.example.yml#L157

done

**Review by slievrly — APPROVED** [review]
LGTM
