### PR TITLE
feature: Implement scheduled handling for end status transaction

### LINKED ISSUE #6875: TimeoutRollbacked and Rollbacked residues
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
TimeoutRollbacked和Rollbacked在db，redis等网络出现问题时，会删除失败，除非重启server，否则这个数据将一直残留，file下如盘满了等情况change status成功后，删除可能就失败了，也会残留
目前DefaultCoordinator中针对committed这种状态是有补偿的，对TimeoutRollbacked和Rollbacked没有任何补偿处理。
In cases where there are network issues with databases, Redis, etc., data may be deleted unsuccessfully and will remain unless the server is restarted. If the disk is full or there are other issues, even after a successful change of status, deletion may fail, leaving the data residual. Currently, in DefaultCoordinator, there is compensation handling for the committed state, but there is no compensation handling for the TimeoutRollbacked and Rollbacked states.
```
    private final GlobalStatus[] retryRollbackingStatuses = new GlobalStatus[] {
        GlobalStatus.TimeoutRollbacking,
        GlobalStatus.TimeoutRollbackRetrying, GlobalStatus.RollbackRetrying};

    private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by YongGoose**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
- Add compensation handling for TimeoutRollbacked and Rollbacked states

### Ⅱ. Does this pull request fix one issue?

fixes #6875

### CODE REVIEW

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 1]
```diff
@@ -189,7 +189,11 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
 
     private final GlobalStatus[] retryRollbackingStatuses = new GlobalStatus[] {
         GlobalStatus.TimeoutRollbacking,
-        GlobalStatus.TimeoutRollbackRetrying, GlobalStatus.RollbackRetrying};
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying,
+        GlobalStatus.TimeoutRollbacked,
+        GlobalStatus.Rollbacked
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: 由于rollback的概率是非常小的，并且rollbacked和TimeoutRollbacked的状态残留的概率更低，故这两种状态是特意放置在server重启时进行处理。
Since the probability of rollback is very low, and the chances of the rollbacked and TimeoutRollbacked states persisting are even lower, these two states are specifically handled during server restart.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: > 由于rollback的概率是非常小的，并且rollbacked和TimeoutRollbacked的状态残留的概率更低，故这两种状态是特意放置在server重启时进行处理。 Since the probability of rollback is very low, and the chances of the rollbacked and TimeoutRollbacked states persisting are even lower, these two states are specifically handled during server restart.

Thank you for your comment :)

I didn’t fully understand.

```
Currently, in DefaultCoordinator, there is compensation handling for the committed state, but there is no compensation handling for the TimeoutRollbacked and Rollbacked states.
```

Based on the comment above, I added these two cases to the array for management.
If any changes are needed, could you please provide additional explanations?

**Comment by YongGoose** [comment]
@funky-eyes 

In the issue description, it was mentioned that the state remains unchanged unless the server is `restarted`.
This means that the data will persist unless the server is restarted.

So, aside from handling it specifically during a server restart, I believe additional measures should be taken.

WDYT?

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 1 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Since the probability of a transaction rollback occurring is very low, the likelihood of the rollbacked intermediate state persisting is even lower. After the rollbacking state, it transitions to rollbacked and is then deleted. These two actions are separated by just one I/O operation, meaning that once the status is successfully updated to rollbacked, the transaction will be immediately deleted, unless a network or storage-side exception occurs during deletion, preventing the transaction from being deleted. Otherwise, there will be no rollbacked transactions left.
The commit of a transaction is a high-probability event, so the likelihood of the committed state persisting is much higher than that of rollbacked. To prevent storage-side pressure and meet performance requirements, committed transactions need to be processed during the server's runtime, while the low-probability rollbacked transactions are handled during the server startup.
Since both of these probabilities are very low, the final result is that they are both deleted. If you think it is necessary to handle rollbacked transactions during runtime, I suggest that you create a separate scheduled task to batch process transactions in the rollbacked and committed states, rather than blocking transactions that urgently need to be rolled back and retried.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: > If you think it is necessary to handle rollbacked transactions during runtime, I suggest that you create a separate scheduled task to batch process transactions in the rollbacked and committed states, rather than blocking transactions that urgently need to be rolled back and retried.

Thank you for your suggestion!

The idea you proposed is very interesting, and I’m planning to work on it. :)

Additionally, I’ve posted a message on the Seata project’s issue list and mailing list regarding this topic.
I’ll leave the links below—could you kindly take a look when you have a chance?
- https://lists.apache.org/thread/xlkshkqs5v2hflp10jgz418kos8vwrsc
- https://github.com/apache/incubator-seata/issues/6774

Thanks again! 🚀

**Comment by funky-eyes** [comment]
Do you use the DingTalk app?

**Comment by YongGoose** [comment]
> Do you use the DingTalk app?

Unfortunately, no.. 

However, if using DingTalk allows for better communication, I’m willing to install it!

**Comment by funky-eyes** [comment]
> > Do you use the DingTalk app?
> 
> Unfortunately, no..
> 
> However, if using DingTalk allows for better communication, I’m willing to install it!

Of course, email is also a great communication channel, but I would like to invite you to join the Seata contributors' DingTalk group if you're willing to install it. If you install it, please send your DingTalk ID to my email, and I will invite you to join the Seata contributors' group.

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 1 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: @funky-eyes 

Done in https://github.com/apache/incubator-seata/pull/7133/commits/fc28796f8009fdecb1dd554c91d461a623d1a050 !
PTAL ⚡️

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java [hunk 2]
```diff
@@ -204,9 +204,17 @@ public boolean isTimeout() {
...
+     *
+     * If the global session's status is "Rollbacked" or "TimeoutRollbacked", it returns the negative time since the session began,
+     * indicating that the session is already dead.
+     * For other statuses, it returns the remaining time until the session reaches the retry dead threshold.
+     *
      * @return time to dead session. if not greater than 0, then deadSession
      */
     public long timeToDeadSession() {
+        if (this.status == GlobalStatus.Rollbacked || this.status == GlobalStatus.TimeoutRollbacked) {
+            return beginTime - System.currentTimeMillis();
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: The beginTime does not change after the creation of the global session, which will cause any global session to be added to the needDoRollbackedSessions list.

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 3]
```diff
@@ -189,12 +197,15 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
...
-        GlobalStatus.TimeoutRollbackRetrying, GlobalStatus.RollbackRetrying};
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying
+    };
 
     private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
 
     private final GlobalStatus[] rollbackingStatuses = new GlobalStatus[] {GlobalStatus.Rollbacking};
     private final GlobalStatus[] committingStatuses = new GlobalStatus[] {GlobalStatus.Committing};
+    private final GlobalStatus[] rollbackedStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.TimeoutRollbacked};
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Why not process transactions in other end states together?

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 4]
```diff
@@ -658,6 +724,8 @@ public void init() {
         rollbackingSchedule(0);
 
         committingSchedule(0);
+
+        rollbackedSchedule(0);
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: The methods `rollbackingSchedule`, `committingSchedule`, and `rollbackedSchedule` need to use the `SessionHolder.distributedLockAndExecute` method to ensure thread safety in a distributed environment.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```java
boolean called = SessionHolder.distributedLockAndExecute(ROLLBACKED, this::handleRollbackedByScheduled);
```

Aren’t we already using `SessionHolder.distributedLockAndExecute`?

Are you suggesting that the `rollbackingSchedule`, `committingSchedule`, and `rollbackedSchedule` methods should be explicitly called using the `SessionHolder.distributedLockAndExecute` API?
> It seems difficult because distributedLockAndExecute requires a parameterless function.

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 2 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: I implemented it this way to set a slightly shorter interval for sessions in the `end` state.

If possible, could you please provide a more detailed explanation? 🙂

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 3 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: I will include the `CommitFailed`, `RollbackFailed`, `TimeoutRollbackFailed`, `Finished`, `CommitRetryTimeout`, and `RollbackRetryTimeout` states :)

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 2 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: The beginTime is set when the transaction is created. When the Seata server's business thread changes the transaction status from "Rollbacking" to "Rollbacked," your timeToDeadSession method directly subtracts the current timestamp from beginTime, which will inevitably result in a negative value. As a result, the business thread will delete the transaction, and your scheduled task will also delete the transaction, leading to a concurrency issue and thread safety problem. I believe that beginTime should be increased by the corresponding transaction timeout, plus an additional buffer time to ensure thread safety.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: Then, would it be appropriate to create a `RETRY_DEAD_THRESHOLD` specifically for the end state?

> Of course, this timeToDeadSession method is more relevant for ongoing statuses like "rollbacking" or "committing." For transactions in the "end" status, I believe the interval can be shortened.

As suggested in the discussion, since we can reduce the interval in the end state, I believe decreasing the size of `RETRY_DEAD_THRESHOLD` could be a reasonable approach.

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 4 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Sorry, I misread it. The issue I mentioned does not exist.

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 2 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: > The beginTime is set when the transaction is created. When the Seata server's business thread changes the transaction status from "Rollbacking" to "Rollbacked," your timeToDeadSession method directly subtracts the current timestamp from beginTime, which will inevitably result in a negative value. As a result, the business thread will delete the transaction, and your scheduled task will also delete the transaction, leading to a concurrency issue and thread safety problem. I believe that beginTime should be increased by the corresponding transaction timeout, plus an additional buffer time to ensure thread safety.

Since our comments were written at the same time, I didn’t see yours when I was writing mine. 😅

Thank you for the additional explanation!
In that case, I will adjust the execution interval for sessions in the `end state` to be shorter using an `if` condition.

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 4 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: > Sorry, I misread it. The issue I mentioned does not exist.

No worries! 🙂

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 2 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: > RETRY_DEAD_THRESHOLD

I think this can be done this way

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: > > RETRY_DEAD_THRESHOLD
> 
> I think this can be done this way

Then no changes required?

> Then, would it be appropriate to create a RETRY_DEAD_THRESHOLD specifically for the end state?

or you mean this way?

Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: Create a corresponding RETRY_DEAD_THRESHOLD for the end state

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 3 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/a9ec30f61e8d70815ca73e21f7dd22c54f5bb5ab !

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 2 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/997775c07c4e946b39e4cc85cd9a42dc79c3d145 !

PTAL ⚡️

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 5]
```diff
@@ -189,12 +197,17 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
...
-        GlobalStatus.TimeoutRollbackRetrying, GlobalStatus.RollbackRetrying};
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying
+    };
 
     private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
 
     private final GlobalStatus[] rollbackingStatuses = new GlobalStatus[] {GlobalStatus.Rollbacking};
     private final GlobalStatus[] committingStatuses = new GlobalStatus[] {GlobalStatus.Committing};
+    private final GlobalStatus[] rollbackedStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.TimeoutRollbacked,
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    private final GlobalStatus[] endStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.TimeoutRollbacked,
```

File: common/src/main/java/org/apache/seata/common/ConfigurationKeys.java [hunk 6]
```diff
@@ -475,6 +475,11 @@ public interface ConfigurationKeys {
      */
     String ROLLBACKING_RETRY_PERIOD = RECOVERY_PREFIX + "rollbackingRetryPeriod";
 
+    /**
+     * The constant ROLLBACKED_RETRY_PERIOD.
+     */
+    String ROLLBACKED_RETRY_PERIOD = RECOVERY_PREFIX + "rollbackedRetryPeriod";
```
Comment (funky-eyes) [inline common/src/main/java/org/apache/seata/common/ConfigurationKeys.java]: https://github.com/apache/incubator-seata/blob/2.x/script/config-center/config.txt
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.example.yml
https://github.com/apache/incubator-seata/blob/2.x/server/src/main/resources/application.raft.example.yml
https://github.com/apache/incubator-seata/blob/2.x/seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/org/apache/seata/spring/boot/autoconfigure/properties/server/ServerProperties.java
This configuration item needs to be supplemented in the above file, and I think it is no longer appropriate to name this configuration starting with `rollback`, because it is a configuration name for handling transactions in the `end` state..

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java [hunk 7]
```diff
@@ -203,13 +211,35 @@ public boolean isTimeout() {
...
+    private boolean isEndStatus() {
+        EnumSet<GlobalStatus> deadStatuses = EnumSet.of(
+            GlobalStatus.Rollbacked,
+            GlobalStatus.TimeoutRollbacked,
+            GlobalStatus.CommitFailed,
+            GlobalStatus.RollbackFailed,
+            GlobalStatus.TimeoutRollbackFailed,
+            GlobalStatus.Finished,
+            GlobalStatus.CommitRetryTimeout,
+            GlobalStatus.RollbackRetryTimeout
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/session/GlobalSession.java]:
```suggestion
            GlobalStatus.Finished
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 8]
```diff
@@ -631,6 +645,60 @@ private void committingSchedule(long delay) {
             delay, TimeUnit.MILLISECONDS);
     }
 
+    /**
+     * Handle rollbacked by scheduled.
+     */
+    protected void handleRollbackedByScheduled() {
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    protected void handleEndStatesByScheduled() {
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 9]
```diff
@@ -631,6 +645,60 @@ private void committingSchedule(long delay) {
...
+            try {
+                if (isRetryTimeout(now, MAX_ROLLBACK_RETRY_TIMEOUT, rollbackedSession.getBeginTime())) {
+
+                    // commit retry timeout event
+                    SessionHelper.endRollbackFailed(rollbackedSession, true, true);
+
+                    //The function of this 'return' is 'continue'.
+                    return;
+                }
+                core.doGlobalRollback(rollbackedSession, true);
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: It should no longer perform rollback processing. For different states of transactions in the end phase, call the `SessionHelper.endRollbacked` and `SessionHelper.endCommitted` methods respectively.

File: common/src/main/java/org/apache/seata/common/ConfigurationKeys.java (hunk 6 above)
Comment (YongGoose) [reply common/src/main/java/org/apache/seata/common/ConfigurationKeys.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/932c51fe7dd96c38d47f06e4e2ee375a9705baa6 !

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 9 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/a7a9e5255b8f235758e9397ef29872f2386735d0 !

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: @funky-eyes 

When you have time, I would appreciate it if you could review this comment and the issue below.
- https://github.com/apache/incubator-seata/issues/6774

File: script/config-center/config.txt [hunk 10]
```diff
@@ -153,6 +153,7 @@ store.redis.queryLimit=100
 server.recovery.committingRetryPeriod=1000
 server.recovery.asynCommittingRetryPeriod=1000
 server.recovery.rollbackingRetryPeriod=1000
+server.recovery.endstatusRetryPeriod=1000
```
Comment (funky-eyes) [inline script/config-center/config.txt:156]:
```suggestion
server.recovery.endstatusRetryPeriod=10000
```

File: common/src/main/java/org/apache/seata/common/DefaultValues.java [hunk 11]
```diff
@@ -397,6 +402,11 @@ public interface DefaultValues {
      */
     int DEFAULT_ROLLBACKING_RETRY_PERIOD = 1000;
 
+    /**
+     * the constant DEFAULT_END_STATUS_RETRY_PERIOD
+     */
+    int DEFAULT_END_STATUS_RETRY_PERIOD = 1000;
```
Comment (funky-eyes) [inline common/src/main/java/org/apache/seata/common/DefaultValues.java]: I believe that for transactions in the end state, they should not be processed with such high frequency, because the probability of end state transactions not being processed by the business thread is very low. Thirty seconds might be more appropriate.

Comment (YongGoose) [reply common/src/main/java/org/apache/seata/common/DefaultValues.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/05735298ecc9a2f49f05ec9f413289f98931ed49 :)

File: changes/zh-cn/2.x.md [hunk 12]
```diff
@@ -9,6 +9,7 @@
 - [[#7037](https://github.com/apache/incubator-seata/pull/7037)] 支持UndoLog的fury序列化方式
 - [[#7069](https://github.com/apache/incubator-seata/pull/7069)] Raft集群模式支持地址转换
 - [[#7038](https://github.com/apache/incubator-seata/pull/7038)] 支持Fury序列化器
+- [[#7133](https://github.com/apache/incubator-seata/pull/7133)] 实现对已回滚和超时回滚事务的定时处理
```
Comment (funky-eyes) [inline changes/zh-cn/2.x.md]:
```suggestion
- [[#7133](https://github.com/apache/incubator-seata/pull/7133)] 实现对残留的end状态事务定时处理
```

File: common/src/main/java/org/apache/seata/common/DefaultValues.java [hunk 13]
```diff
@@ -397,6 +402,11 @@ public interface DefaultValues {
      */
     int DEFAULT_ROLLBACKING_RETRY_PERIOD = 1000;
 
+    /**
+     * the constant DEFAULT_END_STATUS_RETRY_PERIOD
+     */
+    int DEFAULT_END_STATUS_RETRY_PERIOD = 30;
```
Comment (funky-eyes) [inline common/src/main/java/org/apache/seata/common/DefaultValues.java]:
```suggestion
    int DEFAULT_END_STATUS_RETRY_PERIOD = 30 * 1000;
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 14]
```diff
@@ -631,6 +644,64 @@ private void committingSchedule(long delay) {
...
+        SessionHelper.forEach(needDoRollbackedSessions, rollbackedSession -> {
+            try {
+                if (isRetryTimeout(now, MAX_ROLLBACK_RETRY_TIMEOUT, rollbackedSession.getBeginTime())) {
+                    handleEndStateSession(rollbackedSession);
+                }
+            } catch (TransactionException ex) {
+                LOGGER.error("Failed to handle rollbacked [{}] {} {}", rollbackedSession.getXid(), ex.getCode(), ex.getMessage());
+            }
+        });
+        rollbackedSchedule(delay);
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
        endSchedule(delay);
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 15]
```diff
@@ -631,6 +644,64 @@ private void committingSchedule(long delay) {
...
+    }
+
+    private void handleEndStateSession(GlobalSession globalSession) throws TransactionException {
+        GlobalStatus status = globalSession.getStatus();
+
+        if (status == GlobalStatus.CommitFailed) {
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: The commit state is not limited to just one, and the rollback state is the same. I suggest putting the handling of various end states directly in the SessionHelper, and then calling it from handleEndStateSession. The only input parameter needed is a globalsession

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 16]
```diff
@@ -631,6 +644,64 @@ private void committingSchedule(long delay) {
...
+            SessionHelper.endCommitted(globalSession, true);
+            return;
+        }
+        SessionHelper.endRollbacked(globalSession, true);
+    }
+
+    private void rollbackedSchedule(long delay) {
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    private void endSchedule(long delay) {
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 17]
```diff
@@ -631,6 +644,64 @@ private void committingSchedule(long delay) {
...
+        syncProcessing.schedule(
+            () -> {
+                boolean called = SessionHolder.distributedLockAndExecute(ROLLBACKED, this::handleEndStatesByScheduled);
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
                boolean called = SessionHolder.distributedLockAndExecute(END, this::handleEndStatesByScheduled);
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 15 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: As I understand it, instead of directly managing the transaction end states with conditional statements in `handleEndStateSession`, the `responsibility` is being delegated to `SessionHelper`.

Is my understanding correct?

Below is the implementation based on my understanding.

```java
private void handleEndStateSession(GlobalSession globalSession) throws TransactionException {
    SessionHelper.processEndState(globalSession);
}
```

**The state values are just examples.**
```java
public class SessionHelper {

    public static void processEndState(GlobalSession globalSession) throws TransactionException {
        GlobalStatus status = globalSession.getStatus();

        switch (status) {
            case Committed:
            case CommitSuccess:
                endCommitted(globalSession, false);
                break;

            case CommitFailed:
            case CommitPending:
                endCommitted(globalSession, true);
                break;

            case Rollbacked:
            case RollbackSuccess:
                endRollbacked(globalSession, false);
                break;

            case RollbackFailed:
            case RollbackPending:
                endRollbacked(globalSession, true);
                break;

            default:
                log.warn("Unknown transaction state: {}", status);
        }
    }
}
```

Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Yes, I think it should be this way, encapsulating the processing logic in the SessionHelper to hide the internal implementation from the outside.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: Done in https://github.com/apache/incubator-seata/pull/7133/commits/5837ae6b0e090af8cbe435f47528a40f68d6feaf !

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java (hunk 8 above)
Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]: @funky-eyes 

Is there a specific reason why you used `state` instead of `status`?

**Comment by YongGoose** [comment]
@funky-eyes 

You can see in the comment that the word `rollbacked` has been changed to `status`.  https://github.com/apache/incubator-seata/pull/7133/commits/113a7fd66cfad29f76c64dd577fb86b021619358

Please take a look and provide your feedback.

File: server/src/main/java/org/apache/seata/server/session/SessionHelper.java [hunk 18]
```diff
@@ -454,6 +454,25 @@ public static void removeAllBranch(GlobalSession globalSession, boolean isAsync)
         }
     }
 
+    public static void processEndState(GlobalSession globalSession) throws TransactionException {
+        GlobalStatus globalStatus = globalSession.getStatus();
+
+        switch (globalStatus) {
+            case CommitFailed:
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/session/SessionHelper.java]:
```suggestion
            case Committed:
```

File: server/src/main/java/org/apache/seata/server/session/SessionHelper.java [hunk 19]
```diff
@@ -454,6 +454,25 @@ public static void removeAllBranch(GlobalSession globalSession, boolean isAsync)
...
+            case Finished:
+                endCommitted(globalSession, true);
+                return;
+            case Rollbacked:
+            case TimeoutRollbacked:
+            case RollbackFailed:
+            case TimeoutRollbackFailed:
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/session/SessionHelper.java]:
```suggestion
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 20]
```diff
@@ -189,12 +197,16 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
...
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying
+    };
 
     private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
 
     private final GlobalStatus[] rollbackingStatuses = new GlobalStatus[] {GlobalStatus.Rollbacking};
     private final GlobalStatus[] committingStatuses = new GlobalStatus[] {GlobalStatus.Committing};
+    private final GlobalStatus[] endStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.TimeoutRollbacked,
+        GlobalStatus.CommitFailed, GlobalStatus.RollbackFailed, GlobalStatus.TimeoutRollbackFailed, GlobalStatus.Finished};
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    private final GlobalStatus[] endStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.Committed, GlobalStatus.Finished};
```

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 21]
```diff
@@ -189,12 +197,16 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
 
     private final GlobalStatus[] retryRollbackingStatuses = new GlobalStatus[] {
         GlobalStatus.TimeoutRollbacking,
-        GlobalStatus.TimeoutRollbackRetrying, GlobalStatus.RollbackRetrying};
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying
+    };
 
     private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
```
Comment (funky-eyes) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying};
```

**Review by funky-eyes — COMMENTED** [review]
I believe the `committed` state should be handled within the `end` state task, and transactions in a failed state should not be retried. Failed transactions need to be addressed by the operations team, rather than being handled by scheduled tasks.

**Comment by YongGoose** [comment]
> I believe the `committed` state should be handled within the `end` state task, and transactions in a failed state should not be retried. Failed transactions need to be addressed by the operations team, rather than being handled by scheduled tasks.

Good idea!
I agree with you

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java [hunk 22]
```diff
@@ -203,13 +211,33 @@ public boolean isTimeout() {
...
 
+    private boolean isEndStatus() {
+        EnumSet<GlobalStatus> deadStatuses = EnumSet.of(
+            GlobalStatus.Rollbacked,
+            GlobalStatus.TimeoutRollbacked,
+            GlobalStatus.CommitFailed,
+            GlobalStatus.RollbackFailed,
+            GlobalStatus.TimeoutRollbackFailed,
+            GlobalStatus.Finished
+        );
```
Comment (YongGoose) [inline server/src/main/java/org/apache/seata/server/session/GlobalSession.java]:
```suggestion
        EnumSet<GlobalStatus> endStatuses = EnumSet.of(
            GlobalStatus.Rollbacked,
            GlobalStatus.TimeoutRollbacked,
            GlobalStatus.Committed,
            GlobalStatus.Finished
        );
```

@funky-eyes 

WDYT?

**Comment by YongGoose** [comment]
> I believe the `committed` state should be handled within the `end` state task, and transactions in a failed state should not be retried. Failed transactions need to be addressed by the operations team, rather than being handled by scheduled tasks.

That sounds like a good point.

However, while going through your comment, a few questions came to mind:
1. Could you explain the situations where retrying the `endStatus` session would be necessary?
2. If that approach is taken, does it still fail to resolve the `issue` mentioned?
- https://github.com/apache/incubator-seata/issues/6875
3. Lastly, was this PR ultimately decided to simply retry the end status session, or was there another approach considered?

> I completely agree that failed transactions should not be retried but should instead be handled by the operations team. However, I’m curious about how the issue is addressed, so I wanted to ask.

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 22 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: This is okay

**Comment by funky-eyes** [comment]
For the reasons I mentioned earlier:
1. IO exceptions, such as disk or network issues
2. Process crashes (whether it's the seata-server or the database, etc.)

In the above points or some examples I did not mention, transactions are not deleted in the end state, leaving residual data.

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java (hunk 22 above)
Comment (funky-eyes) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: Sorry, I think I missed TimeoutRollbacked. Since TimeoutRollbacked is not a failed end state, it should be handled by scheduled tasks.

Comment (YongGoose) [reply server/src/main/java/org/apache/seata/server/session/GlobalSession.java]: No worries 😉
I'll fix it.

File: server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java [hunk 23]
```diff
@@ -189,12 +197,15 @@ public class DefaultCoordinator extends AbstractTCInboundHandler implements Tran
...
+        GlobalStatus.TimeoutRollbackRetrying,
+        GlobalStatus.RollbackRetrying
+    };
 
-    private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying, GlobalStatus.Committed};
+    private final GlobalStatus[] retryCommittingStatuses = new GlobalStatus[] {GlobalStatus.CommitRetrying};
 
     private final GlobalStatus[] rollbackingStatuses = new GlobalStatus[] {GlobalStatus.Rollbacking};
     private final GlobalStatus[] committingStatuses = new GlobalStatus[] {GlobalStatus.Committing};
+    private final GlobalStatus[] endStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.Committed, GlobalStatus.Finished};
```
Comment (YongGoose) [inline server/src/main/java/org/apache/seata/server/coordinator/DefaultCoordinator.java]:
```suggestion
    private final GlobalStatus[] endStatuses = new GlobalStatus[] {GlobalStatus.Rollbacked, GlobalStatus.TimeoutRollbacked, GlobalStatus.Committed, GlobalStatus.Finished};
```

File: server/src/main/java/org/apache/seata/server/session/SessionHelper.java [hunk 24]
```diff
@@ -454,6 +454,22 @@ public static void removeAllBranch(GlobalSession globalSession, boolean isAsync)
...
+    public static void processEndState(GlobalSession globalSession) throws TransactionException {
+        GlobalStatus globalStatus = globalSession.getStatus();
+
+        switch (globalStatus) {
+            case Committed:
+            case Finished:
+                endCommitted(globalSession, true);
+                return;
+            case Rollbacked:
+                endRollbacked(globalSession, true);
```
Comment (YongGoose) [inline server/src/main/java/org/apache/seata/server/session/SessionHelper.java]:
```suggestion
            case Rollbacked:
            case TimeoutRollbacked:
                endRollbacked(globalSession, true);
```

**Review by YongGoose — COMMENTED** [review]
@funky-eyes 

Please take a look :)
If everything looks good, please proceed with committing the suggestion.

File: server/src/main/java/org/apache/seata/server/session/GlobalSession.java [hunk 25]
```diff
@@ -203,13 +211,31 @@ public boolean isTimeout() {
...
     }
 
+    private boolean isEndStatus() {
+        EnumSet<GlobalStatus> endStatuses = EnumSet.of(
+            GlobalStatus.Rollbacked,
+            GlobalStatus.TimeoutRollbacked,
+            GlobalStatus.Committed,
+            GlobalStatus.Finished
+        );
+        return deadStatuses.contains(this.status);
```
Comment (YongGoose) [inline server/src/main/java/org/apache/seata/server/session/GlobalSession.java]:
```suggestion
        return endStatuses.contains(this.status);
```

**Comment by YongGoose** [comment]
@funky-eyes 

Is there anything else left to do?

**Review by funky-eyes — APPROVED** [review]
LGTM
