### PR TITLE
optimize: Log args mismatch

### LINKED ISSUE #6877: Fewer arguments provided (3) than placeholders specified (4)
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
image

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by arrrnold17**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
Resolved a logging error in the LOGGER.error() method where the number of placeholders did not match the number of provided arguments

### Ⅱ. Does this pull request fix one issue?
fixed #6877

### CODE REVIEW

File: core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientChannelManager.java [hunk 1]
```diff
@@ -244,7 +245,7 @@ void doReconnect(List<String> availList, String transactionServiceGroup) {
                 } else if (LOGGER.isDebugEnabled()) {
                     failedMap.forEach((key, value) -> {
                         LOGGER.error("{} can not connect to {} cause:{} trace information:{}",
-                                FrameworkErrorCode.NetConnect.getErrCode(), key, value.getMessage(), value);
+                                FrameworkErrorCode.NetConnect.getErrCode(), key, value.getMessage(), Arrays.toString(value.getStackTrace()));
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientChannelManager.java]: 我认为不应该改动248行，而是将247行中的trace information:{}改为trace information:
I think we should not make any changes to line 248, but instead change line 247 from "trace information:{}" to "trace information:".

File: core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientChannelManager.java [hunk 2]
```diff
@@ -24,6 +24,7 @@
 import java.util.List;
 import java.util.Map;
 import java.util.Set;
+import java.util.Arrays;
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientChannelManager.java]:
```suggestion
```

**Review by funky-eyes — COMMENTED** [review]
https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md
https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md
请在上述md文件中登记pr信息和作者信息
Please register pr information and author information in the above md file

**Comment by funky-eyes** [comment]
> https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md 请在上述md文件中登记pr信息和作者信息 Please register pr information and author information in the above md file

请看下这条信息
Please take a look at this message.

**Review by funky-eyes — APPROVED** [review]
LGTM
