### PR TITLE
optimize: Compatible with the SPI 、saga、spring module

### LINKED ISSUE #6428: StateMachineDBTests  UT failed
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

image
https://github.com/apache/incubator-seata/actions/runs/8278329860/job/22650441488?pr=6412

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by wt-better**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
fixes #6428
1. Compatible with the SPI module, loads all extensions of io.seata and apache seata, and ensures that io.seata takes precedence under the same name. It should be noted that if the io.seata compatible interface is not inherited from apache.seata, only apache will be loaded. extension of seata

2. Compatible with saga module and add related single tests

3. Compatible with the enableDatasourceProxy annotation and GlobalTransactionScaner of the spring module

--------------
1、兼容SPI模块，加载io.seata和apache seata的所有扩展，并且保证相同名称下io.seata优先，需要注意的是如果io.seata兼容的接口不是继承自apache.seata，仅会加载apache.seata的扩展

2、兼容saga模块，增加相关单测

3、兼容spring模块的enableDatasourceProxy注解和GlobalTransactionScaner

### CODE REVIEW

File: common/src/main/java/org/apache/seata/common/loader/EnhancedServiceLoader.java [hunk 1]
```diff
@@ -616,8 +525,17 @@ private List<ExtensionDefinition<S>> findAllExtensionDefinition(ClassLoader load
...
+            try {
+                return Class.forName(ioSeataType);
+            } catch (ClassNotFoundException e) {
+                return null;
+            }
+        }
+
 
-        private void loadFile(String dir, ClassLoader loader, List<ExtensionDefinition<S>> extensions)
+        private void loadFile(String dir, Class type, ClassLoader loader, List<ExtensionDefinition<S>> extensions)
```
Comment (slievrly) [inline common/src/main/java/org/apache/seata/common/loader/EnhancedServiceLoader.java:538]: It seems that the 'type' parameter is not being used.

File: compatible/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java [hunk 2]
```diff
@@ -16,6 +16,206 @@
...
+
+    public String getSecretKey() {
+        return secretKey;
+    }
+
+    public void setSecretKey(String secretKey) {
+        this.secretKey = secretKey;
+    }
+
+    public void setSagaTransactionalTemplate(SagaTransactionalTemplate sagaTransactionalTemplate) {
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java:187]: It looks like the parameter should be io.seata.saga.engine.tm.SagaTransactionalTemplate.

File: common/src/main/java/org/apache/seata/common/loader/EnhancedServiceLoader.java (hunk 1 above)
Comment (wt-better) [reply common/src/main/java/org/apache/seata/common/loader/EnhancedServiceLoader.java:538]: it`s use for load for SPI Compatible

File: compatible/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+
+    public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode) {
+        super(applicationId, txServiceGroup, mode);
+    }
+
+    public GlobalTransactionScanner(String applicationId, String txServiceGroup, FailureHandler failureHandlerHook) {
+        super(applicationId, txServiceGroup, failureHandlerHook);
+    }
+
+    public GlobalTransactionScanner(String applicationId, String txServiceGroup, int mode, FailureHandler failureHandlerHook) {
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java:53]: the origin `FailureHandler` is io.seata.tm.api.FailureHandler

File: compatible/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineInstanceImpl.java [hunk 4]
```diff
@@ -121,7 +125,11 @@ public ExecutionStatus getCompensationStatus() {
 
     @Override
     public void setCompensationStatus(ExecutionStatus compensationStatus) {
-        actual.setCompensationStatus(compensationStatus.unwrap());
+        if (compensationStatus == null) {
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineInstanceImpl.java:128]: Pls check StateMachineInstanceImpl#L206,L211

File: compatible/src/main/java/io/seata/saga/rm/SagaResourceManager.java
Comment (ptyin) [inline compatible/src/main/java/io/seata/saga/rm/SagaResourceManager.java:1]: Why not just extends `org.apache.seata.saga.rm.SagaResourceManager`

File: saga/seata-saga-rm/src/main/java/org/apache/seata/saga/rm/StateMachineEngineHolder.java [hunk 5]
```diff
@@ -29,7 +29,7 @@ public static StateMachineEngine getStateMachineEngine() {
         return stateMachineEngine;
     }
 
-    public static void setStateMachineEngine(StateMachineEngine smEngine) {
+    public static void  setStateMachineEngine(StateMachineEngine smEngine) {
```
Comment (xingfudeshi) [inline saga/seata-saga-rm/src/main/java/org/apache/seata/saga/rm/StateMachineEngineHolder.java]: Only one space.

File: compatible/src/test/java/io/seata/saga/engine/mock/DemoService.java [hunk 6]
```diff
@@ -0,0 +1,187 @@
...
+        }
+        else {
+            throw new RuntimeException(new ConnectException("Connect Exception"));
+        }
+    }
+
+    public static class People {
+
+        private String name;
+        private int    age;
```
Comment (xingfudeshi) [inline compatible/src/test/java/io/seata/saga/engine/mock/DemoService.java]: Single space

File: compatible/src/main/java/io/seata/saga/rm/SagaResourceManager.java
Comment (wt-better) [reply compatible/src/main/java/io/seata/saga/rm/SagaResourceManager.java:1]: Because the classpath of ExecutionStatus、TransactionException、StateMachineEngineHolderhave changed, they cannot inherited. this impl is more convenient.

File: compatible/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java (hunk 2 above)
Comment (wt-better) [reply compatible/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java:187]: compatibility 'sagaTransactionalTemplate' will be more complicated. For example, if you need to be compatible with sagaTransactionalTemplate ,must compatible TransactionalExecutor -> compatible with TransactionInfo -> compatible with TransactionInfo RollbackRule and LockStrategyMode etc class in TransactionInfo.

Considering that it is rarely used, it is decided not to be compatible in this pr.

File: compatible/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java (hunk 3 above)
Comment (wt-better) [reply compatible/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java:53]: i will fix it

File: compatible/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineInstanceImpl.java (hunk 4 above)
Comment (wt-better) [reply compatible/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineInstanceImpl.java:128]: fixed. compatible with stateMachine

File: compatible/src/test/java/io/seata/common/LockAndCallback.java [hunk 7]
```diff
@@ -0,0 +1,99 @@
...
+import io.seata.saga.statelang.domain.ExecutionStatus;
+import io.seata.saga.statelang.domain.StateMachineInstance;
+
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.locks.Condition;
+import java.util.concurrent.locks.Lock;
+import java.util.concurrent.locks.ReentrantLock;
+
+/**
+ */
```
Comment (funky-eyes) [inline compatible/src/test/java/io/seata/common/LockAndCallback.java]:
```suggestion
```

**Review by xingfudeshi — APPROVED** [review]
LGTM

**Review by funky-eyes — APPROVED** [review]
LGTM
