### PR TITLE
bugfix: ensure visibility of rm and The methods in MockTest are executed in order

### LINKED ISSUE #7558: Test Failure: io.seata.MockTest.testRollback Fails with RPC Timeout
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [ ] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

During the GitHub Actions CI run ([link to job](https://github.com/apache/incubator-seata/actions/runs/16547019230/job/46796366972?pr=7492)), the test io.seata.MockTest.testRollback fails consistently due to an RPC Timeout. The failure log indicates the following error:

```
io.seata.core.exception.TransactionException: RPC Timeout
    at io.seata.MockTest.testRollback ...
```

### Ⅱ. Describe what happened

- Multiple configuration properties under transport.* and server.* are missing in the logs, leading to the use of default values.
- There are repeated errors loading configuration providers (e.g., Nacos provider not found).
- The mock server on 127.0.0.1:8077 may not be properly set up or reachable during the test, leading to Netty channel timeouts and closures.
- The failure always occurs after a 30-second wait, suggesting a network or setup problem rather than a code logic issue.

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

_No response_

### PR DESCRIPTION
**Pull request by maple525866**
- [x] I have read the [CONTRIBUTING.md](https://github.com/apache/incubator-seata/blob/2.x/CONTRIBUTING.md) guidelines.
- [x] I have registered the PR [changes](https://github.com/apache/incubator-seata/tree/2.x/changes).

### Ⅰ. Describe what this PR did
#7585 
With the help of @funky-eyes's analysis, I think it is not a network or port problem, but a visibility problem.
Because the rm member variable in RmClientTest is not declared as volatile, this may cause the rm variable to be modified multiple times during concurrent testing, thus causing this problem。

Here is the fix I made for the problem:
- The volatile keyword ensures that writes to the rm variable are immediately visible to all threads, preventing instruction reordering. 
- Test ordering: The @TestMethodOrder and @Order annotations ensure that tests are executed sequentially, avoiding concurrent access issues. 
- Double-checked locking safety: volatile + synchronized ensures thread-safe lazy loading.

### Ⅱ. Does this pull request fix one issue?

fixes #7558 

### Ⅳ. Describe how to verify it
mvn clean test

### CODE REVIEW

File: test-old-version/src/test/java/io/seata/MockTest.java [hunk 1]
```diff
@@ -29,16 +29,14 @@
 import io.seata.rm.DefaultResourceManager;
 import org.apache.seata.mockserver.MockCoordinator;
 import org.apache.seata.mockserver.MockServer;
-import org.junit.jupiter.api.AfterAll;
-import org.junit.jupiter.api.Assertions;
-import org.junit.jupiter.api.BeforeAll;
-import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.*;
```
Comment (funky-eyes) [inline test-old-version/src/test/java/io/seata/MockTest.java]: Please don't use wildcard imports

**Review by funky-eyes — APPROVED** [review]
LGTM
