### PR TITLE
optimize: undo_log table check optimize

### LINKED ISSUE #6022: [Optimize] add a check for the existence of the undolog table
## Why you need it?
When proxying the datasourceProxy, a check is performed to see if the undolog table exists. If it doesn't exist, an exception is thrown as a prompt. Remember to add a check switch, as it's possible that a user may only use the TCC mode but inadvertently enable the check switch.

## How it could be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

### PR DESCRIPTION
**Pull request by laywin**
- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
https://github.com/seata/seata/issues/6022

### Ⅱ. Does this pull request fix one issue?

fixes #6022

### CODE REVIEW

File: rm-datasource/src/test/java/io/seata/rm/RMHandlerATTest.java
Comment (funky-eyes) [inline rm-datasource/src/test/java/io/seata/rm/RMHandlerATTest.java:1]: Write a test case for the newly modified code.

Comment (laywin) [reply rm-datasource/src/test/java/io/seata/rm/RMHandlerATTest.java:1]: done

File: changes/zh-cn/2.x.md [hunk 1]
```diff
@@ -9,7 +9,7 @@
 - [[#PR_NO](https://github.com/seata/seata/pull/PR_NO)] 准确简要的PR描述
 
 ### optimize:
-- [[#PR_NO](https://github.com/seata/seata/pull/PR_NO)] 准确简要的PR描述
+- [[#6031](https://github.com/seata/seata/pull/6031)] 添加undo_log表的存在性校验
```
Comment (funky-eyes) [inline changes/zh-cn/2.x.md:12]: 该版本下首次提交pr，作者信息需要进行登记一下
For the first PR submission in this version, the author's information needs to be registered.

File: rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java [hunk 2]
```diff
@@ -143,6 +153,32 @@ private boolean isPolardbXProduct() {
...
+     *
+     * @param conn db connection
+     */
+    private void checkUndoLogTableExist(Connection conn) {
+        if (DBType.optionalof(dbType).isPresent()) {
+            UndoLogManager undoLogManager;
+            try {
+                undoLogManager = UndoLogManagerFactory.getUndoLogManager(dbType);
+            } catch (EnhancedServiceNotFoundException e) {
+                LOGGER.error("can't find undoLogManager service provider for dbtype: {}", dbType);
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java]: 我建议这里直接抛异常出去，说明用户再使用一个我们不支持的数据库，要提示这个数据库不支持
I suggest throwing an exception directly here, indicating that if the user uses a database that we do not support, we need to prompt that the database is not supported.

File: changes/zh-cn/2.x.md (hunk 1 above)
Comment (laywin) [reply changes/zh-cn/2.x.md:12]: 是这个吗，有登记额
Is this it? It's registered
image

File: rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java (hunk 2 above)
Comment (laywin) [reply rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java]: 没有抛出去，是因为很多单测使用了数据库代理，会导致单测失败。
It is not thrown out because many unit tests use database proxy, which can be lead it fail.

Comment (funky-eyes) [reply rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java]: > 没有抛出去，是因为很多单测使用了数据库代理，会导致单测失败。 It is not thrown out because many unit tests use database proxy, which can be lead it fail.

有没有什么办法在单测的时候不进行校验undolog table？或者增加一个开关，这个开关允许用户配置check，如果用户关闭，就不进行check，然后我们默认开启，在单测的时候关闭check
Is there any way to not check undolog table during single test or add a switch that allows user to configure check and if user turns it off, no check is performed, then we turn it on by default and turn off check during single test

File: changes/zh-cn/2.x.md (hunk 1 above)
Comment (funky-eyes) [reply changes/zh-cn/2.x.md:12]: 你看下中文的那份文件是否没登记
Check if the Chinese file is not registered.

Comment (laywin) [reply changes/zh-cn/2.x.md:12]: done

File: rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java (hunk 2 above)
Comment (laywin) [reply rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java]: update mockito version to 4.5.1 same as seata server's mockito dependency to support static mock. when unit test. mock undolog table check.

**Review by funky-eyes — APPROVED** [review]
LGTM
