### PR TITLE
bugfix: the failure of rollbacking back of the delete SQL at AT mode when using SQLServer

### LINKED ISSUE #6449: seata2.1.0 服务端用mysql+SqlServer业务端  主键使用雪花算法，回滚事务报没有标识属性。无法执行 SET 操作
2024-03-28 13:52:50.385 ERROR 11556 --- [_RMROLE_1_16_16] i.seata.rm.datasource.DataSourceManager  : [stacktrace]branchRollback failed. branchType:[AT], xid:[192.168.1.5:8091:6629803150973841558], branchId:[6629803150973841560], resourceId:[jdbc:sqlserver://sqlserver:1433;databaseName=DL_CP_WMS_DEVICE], applicationData:[null]. reason:[Branch session rollback failed and try again later xid = 192.168.1.5:8091:6629803150973841558 branchId = 6629803150973841560 表 'rf_collection' 没有标识属性。无法执行 SET 操作。]

io.seata.core.exception.BranchTransactionException: Branch session rollback failed and try again later xid = 192.168.1.5:8091:6629803150973841558 branchId = 6629803150973841560 表 'rf_collection' 没有标识属性。无法执行 SET 操作。
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:370)
	at io.seata.rm.datasource.DataSourceManager.branchRollback(DataSourceManager.java:122)
	at io.seata.rm.AbstractRMHandler.doBranchRollback(AbstractRMHandler.java:125)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:67)
	at io.seata.rm.AbstractRMHandler$2.execute(AbstractRMHandler.java:63)
	at io.seata.core.exception.AbstractExceptionHandler.exceptionHandleTemplate(AbstractExceptionHandler.java:131)
	at io.seata.rm.AbstractRMHandler.handle(AbstractRMHandler.java:63)
	at io.seata.rm.DefaultRMHandler.handle(DefaultRMHandler.java:68)
	at io.seata.core.protocol.transaction.BranchRollbackRequest.handle(BranchRollbackRequest.java:35)
	at io.seata.rm.AbstractRMHandler.onRequest(AbstractRMHandler.java:150)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.handleBranchRollback(RmBranchRollbackProcessor.java:63)
	at io.seata.core.rpc.processor.client.RmBranchRollbackProcessor.process(RmBranchRollbackProcessor.java:58)
	at io.seata.core.rpc.netty.AbstractNettyRemoting.lambda$processMessage$2(AbstractNettyRemoting.java:280)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 表 'rf_collection' 没有标识属性。无法执行 SET 操作。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1624)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:473)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3254)
	at com.alibaba.druid.filter.FilterAdapter.preparedStatement_executeUpdate(FilterAdapter.java:1075)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeUpdate(FilterEventAdapter.java:486)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeUpdate(FilterChainImpl.java:3252)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeUpdate(PreparedStatementProxyImpl.java:192)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:241)
	at io.seata.rm.datasource.undo.AbstractUndoExecutor.executeOn(AbstractUndoExecutor.java:137)
	at io.seata.rm.datasource.undo.AbstractUndoLogManager.undo(AbstractUndoLogManager.java:317)
	... 16 common frames omitted

2024-03-28 13:52:50.385  INFO 11556 --- [_RMROLE_1_16_16] io.seata.rm.AbstractRMHandler            : Branch Rollbacked result: PhaseTwo_RollbackFailed_Retryable
2024-03-28 13:52:51.372  INFO 11556 --- [h_RMROLE_1_1_16] i.s.c.r.p.c.RmBranchRollbackProcessor    : rm handle branch rollback process:BranchRollbackRequest{xid='192.168.1.5:8091:6629803150973841558', branchId=6629803150973841560, branchType=AT, resourceId='jdbc:sqlserver://sqlserver:1433;databaseName=DL_CP_WMS_DEVICE', applicationData='null'}

### PR DESCRIPTION
**Pull request by TakeActionNow2019**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
fix the failure of rollbacking back of the delete SQL at AT mode when using SQLServer

### Ⅱ. Does this pull request fix one issue?

fix #6449

### CODE REVIEW

**Comment by TakeActionNow2019** [comment]
At AT mode when using SQLServer, if any column of a table is with "IDENTITY", before inserting a value into this column, we should judge whether there is a "IDENTITY" with it or not. Or the database will report errors, ie "Table 'xxx' does not have the identity property. Cannot perform SET operation"  and "Cannot insert explicit value for identity column in table 'xxx' when IDENTITY_INSERT is set to OFF."

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java [hunk 1]
```diff
@@ -16,21 +16,32 @@
...
 import org.apache.seata.sqlparser.util.JdbcConstants;
 
+import java.sql.Connection;
+import java.sql.PreparedStatement;
+import java.sql.ResultSet;
+import java.sql.SQLException;
+import java.sql.Statement;
+import java.util.ArrayList;
+import java.util.List;
+import java.util.stream.Collectors;
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java]: Please put the Java package at the top level.

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java [hunk 2]
```diff
@@ -16,21 +16,32 @@
...
+
 
 public class SqlServerUndoDeleteExecutor extends BaseSqlServerUndoExecutor {
+
+    private boolean tableIdentifyExistence = false;
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: I hope this variable will eventually be cached in TableMeta and the caching-related refresh and retrieval will be implemented in SqlServerTableMetaCache, rather than in the executor, where it needs to be executed every time executeOn is called.

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: Originally, I  considered putting it in a cache. But then I thought of that the application has to be started again to refresh the cache when a column that has something to do with ""INDENTITY  changed. So I quit to do that. 
Now I rethink that it's probable for a application to restart when a column is changed. 
I will fix it tonight.

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java (hunk 1 above)
Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java]: Done!

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java (hunk 2 above)
Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: Done!
I use the SqlServerTableMetaCache to help me. Please help me reivew it again!
image

Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: My idea is to have `tableIdentifyExistence` handled together with `resultSetMetaToSchema` in `SqlServerTableMetaCache`, rather than handling it separately in `SqlServerUndoDeleteExecutor`.

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: I pondered about it last night. And I found that the cahce key should be a combination of resourceId, schema and table name. It may be a feasible way to put it in the subclass of TableMeta. But when I was creating a subclass of TableMeta named SqlServerTableMeta, I found it a little elegant again. So I make a compromise and fix it in this way. What do you think of it? Any better ideas？

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: There is a typo there. It should be " I found it a little not elegant again". o(╯□╰)o

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: I found it a good way to judge whether  there is a "IDENTITY" in a table by creating a subclass of TableMeta named SqlServerTableMeta with a new filed in it for justification. But I found there are no other subclass of TableMeta for other SQL dialect. Maybe it sounds a bit inelegant, too. What do you think of it? @funky-eyes

Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: > I found it a good way to judge whether there is a "IDENTITY" in a table by creating a subclass of TableMeta named SqlServerTableMeta with a new filed in it for justification. But I found there are no other subclass of TableMeta for other SQL dialect. Maybe it sounds a bit inelegant, too. What do you think of it? @funky-eyes

I think it's possible to create a subclass to provide specific metadata for different databases. I agree with your approach, let's go ahead and do it.

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: Done! Please review! Thanks!

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:44]: @funky-eyes Please help me review! Thanks!

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java [hunk 3]
```diff
@@ -59,17 +71,75 @@ protected String buildUndoSQL() {
...
+     * @throws SQLException the sql exception
+     */
+    @Override
+    public void executeOn(ConnectionProxy connectionProxy) throws SQLException {
+        Connection conn = connectionProxy.getTargetConnection();
+        if (IS_UNDO_DATA_VALIDATION_ENABLE && !dataValidationAndGoOn(connectionProxy)) {
+            return;
+        }
+
+        judgeTableIdentifyExistence(connectionProxy);
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: 我认为这个方法应该放在构造方法中，这样就不需要重写executeOn了
I think this method should be placed in the constructor so that there's no need to override executeOn.

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: Good idea! However, we need to integrate the TableMetaCacheFactory at the same time. To get the TableMeta instance of SqlServer, we need to prepare the dbType, targetConnection and resourceId, which cannot be done with the constructor of SqlServerUndoDeleteExecutor and parameter sqlUndoLog of SQLUndoLog class. So we have to compromise in this way.
image

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: image

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: Please help review, @funky-eyes. Thanks!

Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: > Please help review, @funky-eyes. Thanks!

I've noticed many commits unrelated to this PR. Did you encounter issues with merging locally?

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: Not really. I just puledl the latest code and there were two confilicts, involving \changes\en-us\2.x.md and \changes\zh-cn\2.x.  Then I merged the two files and pushed them. I have no idea why there are so many unrelated commits there. Does it matter? If it matters, what should I do? @funky-eyes

Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: > Not really. I just puledl the latest code and there were two confilicts, involving \changes\en-us\2.x.md and \changes\zh-cn\2.x. Then I merged the two files and pushed them. I have no idea why there are so many unrelated commits there. Does it matter? If it matters, what should I do? @funky-eyes

I suggest you go back to the code first and recombine the submission.

Comment (TakeActionNow2019) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/sqlserver/SqlServerUndoDeleteExecutor.java:112]: done. Please review again! Thanks!

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
Thank you for your contributions to Seata. If possible, please send your Dingtalk contact information to my email, and I will invite you to join the Seata developer group.
[jianbin@apache.org](mailto:jianbin@apache.org)
