### PR TITLE
bugfix: Resolve `NullPointerException` in `EtcdRegistryServiceImplMockTest`

### LINKED ISSUE #7347: EtcdRegistryServiceImplMockTest.testUnsubscribe:237 » NullPointer
Image

Image

### PR DESCRIPTION
**Pull request by YongGoose**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
fixes #7347

### CODE REVIEW

File: discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java [hunk 1]
```diff
@@ -178,7 +181,11 @@ public void unsubscribe(String cluster, Watch.Listener listener) throws Exceptio
                     .collect(Collectors.toSet());
             listenerMap.put(cluster, newSubscribeSet);
         }
-        watcherMap.remove(cluster).stop();
+
+        EtcdWatcher watcher = watcherMap.remove(cluster);
+        if (watcher != null) {
+            watcher.stop();
```
Comment (YongGoose) [inline discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java:187]: @funky-eyes 

I added a null check here, so even if an element is not found in the map, it won't cause a `NullPointerException`.

File: discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java [hunk 2]
```diff
@@ -401,20 +411,24 @@ public EtcdWatcher(String cluster, Watch.Listener listener) {
...
         }
 
         /**
          * stop this task
          */
         public void stop() {
-            this.watcher.close();
+            if (this.watcher != null) {
+                this.watcher.close();
+            }
```
Comment (YongGoose) [inline discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java:431]: @funky-eyes 

I add a null check here. What do you think?

**Comment by YongGoose** [comment]
image

File: discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java (hunk 2 above)
Comment (funky-eyes) [reply discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java:431]: I don't quite understand why the NPE in the unsubscribe is related to this.

Comment (YongGoose) [reply discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java:431]: Currently, the `watcher` is initialized not in the `constructor`, but within the `run` method of the `EtcdWatcher` class.
In the test code, we used `thenAnswer` to return a `mockWatcher`, ensuring that the watcher is properly initialized in the run method. However, when running the test `10,000` times using `@RepeatedTest`, we encountered 7 failures.

All 7 failures were caused by a `NullPointerException` triggered when the `stop` method was called while the watcher was still null.

image


It appears that, intermittently, the unsubscribe method is executed before the run method, leading to this issue.

- After adding a null check in the `stop` method, the issue has not occurred again.\
That's why i believe this piece of code is related to the NPE issue.

Comment (funky-eyes) [reply discovery/seata-discovery-etcd3/src/main/java/org/apache/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java:431]: > Currently, the `watcher` is initialized not in the `constructor`, but within the `run` method of the `EtcdWatcher` class. In the test code, we used `thenAnswer` to return a `mockWatcher`, ensuring that the watcher is properly initialized in the run method. However, when running the test `10,000` times using `@RepeatedTest`, we encountered 7 failures.
> 
> All 7 failures were caused by a `NullPointerException` triggered when the `stop` method was called while the watcher was still null.
> 
> image
> 
> It appears that, intermittently, the unsubscribe method is executed before the run method, leading to this issue.
> 
> * After adding a null check in the `stop` method, the issue has not occurred again.
>   That's why i believe this piece of code is related to the NPE issue.

I understand now, thank you for your explanation.

**Review by funky-eyes — APPROVED** [review]
LGTM
