### PR TITLE
optimize: Add `ChannelEventListener` support to prevent memory leaks

### LINKED ISSUE #5283: ClientOnResponseProcessor#mergeMsgMap&futures is a risk of memory leaks
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
timeout发生如tc网络出现故障或宕机，消息实际上已达到tc时，但无法将response响应时候没有去清除mergemsgmap和futures里的数据，而是单纯的靠server的response下来再remove（详见ClientOnResponseProcessor#process），这带来一个问题，server非优雅下线的时候，这个futures和mergemsgmap无法清理，残留了数据
AbstractNettyRemotingClient#MergedSendRunnable 中也仅对发送失败时清理了futures（该内存泄露问题的前提是client发送成功，tc响应失败），mergemsgmap并没有清理
image

ps：该情况出现概率非常非常低，通过阅读这块代码逻辑偶然发现

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

### Ⅵ. Environment:

- JDK version :
- Seata version:  
- OS :
- Others:

### LINKED ISSUE #7058: RemotingClient does not support setting a listener
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

RemotingClient不支持设置listener，当消息发出后channel断开时，无法通过listener进行快速响应失败。
RemotingClient does not support setting a listener. When the channel is disconnected after the message is sent, it cannot quickly respond to the failure through the listener

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by YongGoose**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #7058 
fixes #5283 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
After the implementation is complete, it will be added.

```mermaid
graph TD;
    A[RemotingClient Interface] -->|implements| B[AbstractNettyRemotingClient];
    C[ChannelEventListener Interface] -->|implements| D[Custom Listener];
    B -->|registerChannelEventListener| C;
    B -->|setChannelHandlers| E[ChannelEventHandler];

    E -->|detects| F1[channelInactive];
    E -->|detects| F2[onChannelException];
    E -->|detects| F3[onChannelActive];
    E -->|detects| F4[onChannelIdle];

    F1 -->|invokes| G[cleanupResourcesForChannel];
    F2 -->|invokes| G;
    G -->|cleans up| H[mergeMsgMap];
    G -->|cleans up| I[futures];

    F1 -->|notifies| C;
    F2 -->|notifies| C;
    F3 -->|notifies| C;
    F4 -->|notifies| C;
```

### CODE REVIEW

**Comment by YongGoose** [comment]
It looks like the `RM`(Resource Manager) registration has failed.
https://github.com/apache/incubator-seata/blob/ac99e5bebe0db8f75763c2e2c0c874df3f2dbb0c/core/src/main/java/org/apache/seata/core/rpc/netty/NettyClientChannelManager.java#L295
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 63.019 s <<< FAILURE! - in org.apache.seata.core.rpc.netty.RmNettyClientTest
org.apache.seata.core.rpc.netty.RmNettyClientTest.testMergeMsg  Time elapsed: 3.015 s  <<< ERROR!
org.apache.seata.common.exception.FrameworkException: can not register RM,err:can not connect to services-server.
	at org.apache.seata.core.rpc.netty.RmNettyClientTest.testMergeMsg(RmNettyClientTest.java:88)
```

**Review by funky-eyes — COMMENTED** [review]
This design is to callback the ChannelEventListener registered by TM and RM, rather than adding a listener after channel.write(), right?

**Comment by YongGoose** [comment]
> This design is to callback the ChannelEventListener registered by TM and RM, rather than adding a listener after channel.write(), right?

Yes, that's correct.

It is implemented in a way that calls back the `ChannelEventListener` registered in advance by TM and RM, so that user-defined actions can be performed when the channel event is detected.

**Comment by funky-eyes** [comment]
> > This design is to callback the ChannelEventListener registered by TM and RM, rather than adding a listener after channel.write(), right?
> 
> Yes, that's correct.
> 
> It is implemented in a way that calls back the `ChannelEventListener` registered in advance by TM and RM, so that user-defined actions can be performed when the channel event is detected.

I think this design is good, but since this functionality is not a user-facing API, it shouldn't be a feature-type PR. I believe it should be changed to an optimize type instead. Could you also fix the codecov/patch issue by adding some test cases to increase coverage? Of course, you could also improve unit test coverage in a subsequent PR.

**Comment by YongGoose** [comment]
> I think this design is good, but since this functionality is not a user-facing API, it shouldn't be a feature-type PR. I believe it should be changed to an optimize type instead. Could you also fix the codecov/patch issue by adding some test cases to increase coverage? Of course, you could also improve unit test coverage in a subsequent PR.

Got it!
I'll update the PR type and add both unit and integration tests. 🚀

**Comment by YongGoose** [comment]
@funky-eyes 

I believe the part I worked on this time is critical and could cause serious issues if a bug occurs. 🐞

That's why I plan to write more comprehensive unit and integration tests to cover a wide range of cases.
As a result, it might take some extra time.

I'll request a review once all the tests are complete!

**Comment by funky-eyes** [comment]
> @funky-eyes
> 
> I believe the part I worked on this time is critical and could cause serious issues if a bug occurs. 🐞
> 
> That's why I plan to write more comprehensive unit and integration tests to cover a wide range of cases. As a result, it might take some extra time.
> 
> I'll request a review once all the tests are complete!

OK, I wish you success. If you have any questions, feel free to contact me.

File: core/src/main/java/org/apache/seata/core/rpc/netty/ChannelEventHandler.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+     * Logs the channel deactivation event and notifies the remoting client.
+     *
+     * @param ctx the channel handler context
+     * @throws Exception if an exception occurs
+     */
+    @Override
+    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
+        Channel channel = ctx.channel();
+        LOGGER.warn("Channel inactive: {}", channel.remoteAddress());
+        remotingClient.onChannelInactive(channel);
```
Comment (YongGoose) [inline core/src/main/java/org/apache/seata/core/rpc/netty/ChannelEventHandler.java:67]: @funky-eyes

I wanted to discuss with you.

Right now, the `handler` is directly invoking the `AbstractNettyRemotingClient`.
To me, it feels like this setup is also playing the role of a `listener`.

As an alternative, the `handler` could call the `AbstractNettyRemotingClient`, while the `listener` handles separate responsibilities.
> I think this task should be designed in a separate issue before we move on to implementation.

What do you think?

File: core/src/test/java/org/apache/seata/core/rpc/netty/ChannelEventHandlerIntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,282 @@
...
+                .filter(ch -> ch.isActive() && ch.remoteAddress() != null)
+                .findFirst()
+                .orElseThrow(() -> new AssertionError("Failed to find client channel on server side"));
+
+        serverSideClientChannel.close().sync();
+        assertTrue(
+                channelInactiveLatch.await(TIMEOUT_SECONDS, TimeUnit.SECONDS),
+                "Channel inactive event was not detected on client side when server closed the connection");
+        verify(mockRemotingClient).onChannelInactive(any(Channel.class));
+    }
```
Comment (YongGoose) [inline core/src/test/java/org/apache/seata/core/rpc/netty/ChannelEventHandlerIntegrationTest.java:212]: Please check whether this test verifies what we're trying to implement in this issue!

File: core/src/main/java/org/apache/seata/core/rpc/netty/RmNettyRemotingClient.java [hunk 3]
```diff
@@ -86,6 +86,24 @@ public void init() {
                 getClientChannelManager().initReconnect(transactionServiceGroup, failFast);
             }
         }
+
+        registerChannelEventListener(new ChannelEventListener() {
+            @Override public void onChannelConnected(Channel channel) {
+                LOGGER.debug("Channel active: {}", channel.remoteAddress());
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/RmNettyRemotingClient.java]: You should first check if the log level is set to debug before printing debug logs.

File: core/src/main/java/org/apache/seata/core/rpc/netty/TmNettyRemotingClient.java [hunk 4]
```diff
@@ -84,6 +84,24 @@ public void onChangeEvent(ConfigurationChangeEvent event) {
                 }
             }
         });
+
+        registerChannelEventListener(new ChannelEventListener() {
+            @Override public void onChannelConnected(Channel channel) {
+                LOGGER.debug("Channel active: {}", channel.remoteAddress());
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/TmNettyRemotingClient.java]: You should first check if the log level is set to debug before printing debug logs.

File: core/src/main/java/org/apache/seata/core/rpc/netty/RmNettyRemotingClient.java (hunk 3 above)
Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/RmNettyRemotingClient.java:92]: Should this be applied to every LOGGER?

Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/RmNettyRemotingClient.java]: Done in https://github.com/apache/incubator-seata/pull/7337/commits/02e4c90d1edaf67cdbf2177f5613997ccf5121a2 !

File: core/src/main/java/org/apache/seata/core/rpc/netty/TmNettyRemotingClient.java (hunk 4 above)
Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/TmNettyRemotingClient.java]: Ditto

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by funky-eyes** [comment]
I would like to know if a PR will be submitted soon to fix the issue mentioned in #5283?

File: core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java [hunk 5]
```diff
@@ -336,6 +345,201 @@ private String getThreadPrefix() {
...
+        Set<Integer> messageIds = new HashSet<>();
+
+        String serverAddress = null;
+        for (Map.Entry<String, Channel> entry : clientChannelManager.getChannels().entrySet()) {
+            Channel channel = entry.getValue();
+            if (channelId.equals(channel.id())) {
+                serverAddress = entry.getKey();
+                break;
+            }
+        }
```
Comment (YongGoose) [inline core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java:456]: @funky-eyes 

I believe this method addresses issue #5283. 
What are your thoughts?

File: core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java [hunk 6]
```diff
@@ -0,0 +1,140 @@
...
+        basketMap.put(serverAddress, basket);
+
+        client.cleanupResourcesForChannel(channel);
+
+        assertFalse(futures.containsKey(1), "Future ID 1 has not been removed");
+        assertFalse(futures.containsKey(2), "Future ID 2 has not been removed");
+
+        assertThrows(RuntimeException.class, () -> messageFuture1.get(0, java.util.concurrent.TimeUnit.MILLISECONDS));
+        assertThrows(RuntimeException.class, () -> messageFuture2.get(0, java.util.concurrent.TimeUnit.MILLISECONDS));
+    }
```
Comment (YongGoose) [inline core/src/test/java/org/apache/seata/core/rpc/netty/ResourceCleanupTest.java:120]: @funky-eyes 

Ditto

**Comment by YongGoose** [comment]
> I would like to know if a PR will be submitted soon to fix the issue mentioned in #5283?

Please take a look
- https://github.com/apache/incubator-seata/pull/7337#discussion_r2097233086
- https://github.com/apache/incubator-seata/pull/7337#discussion_r2097234107

File: core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java [hunk 7]
```diff
@@ -336,6 +345,201 @@ private String getThreadPrefix() {
...
+
+    /**
+     * Cleans up futures for a set of message IDs.
+     * This completes futures with an exception to notify waiting threads.
+     *
+     * @param messageIds the set of message IDs whose futures should be cleaned up
+     * @param cause the exception to set as the result for each future
+     */
+    private void cleanupFuturesForMessageIds(Set<Integer> messageIds, Exception cause) {
+        for (Integer messageId : messageIds) {
```
Comment (funky-eyes) [inline core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java:489]:
```
    @Override
    public void sendAsyncRequest(Channel channel, Object msg) {
        if (channel == null) {
            LOGGER.warn("sendAsyncRequest nothing, caused by null channel.");
            throw new FrameworkException(new Throwable("throw"), "frameworkException", FrameworkErrorCode.ChannelIsNotWritable);
        }
        RpcMessage rpcMessage = buildRequestMessage(msg, msg instanceof HeartbeatMessage
            ? ProtocolConstants.MSGTYPE_HEARTBEAT_REQUEST
            : ProtocolConstants.MSGTYPE_RESQUEST_ONEWAY);
        Object body = rpcMessage.getBody();
        if (body instanceof MergeMessage) {
            Integer parentId = rpcMessage.getId();
            mergeMsgMap.put(parentId, (MergeMessage)rpcMessage.getBody());
            if (body instanceof MergedWarpMessage) {
                for (Integer msgId : ((MergedWarpMessage)rpcMessage.getBody()).msgIds) {
                    childToParentMap.put(msgId, parentId);
                }
            }
        }
        super.sendAsync(channel, rpcMessage);
    }
```
It seems that childToParentMap is not being cleared.

Comment (YongGoose) [reply core/src/main/java/org/apache/seata/core/rpc/netty/AbstractNettyRemotingClient.java:489]: I'll create a PR that also clears the `childToParentMap` as soon as possible—hopefully by tomorrow.
