### PR TITLE
optimize: compatible with integration-tx-api module and spring module

### LINKED ISSUE #6334: Compatible with integration-tx-api module
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### LINKED ISSUE #6335: Compatible with spring module
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by xingfudeshi**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #6334
fixes #6335

### CODE REVIEW

**Review by slievrly — COMMENTED** [review]
some checkstyle failed.
image

**Comment by xingfudeshi** [comment]
> some checkstyle failed.
> 
> image
> 
> 

ok

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+     *
+     * @param paramType     the param type, 'param' or 'field'
+     * @param paramName     the param name
+     * @param paramValue    the param value
+     * @param annotation    the annotation on the param or field
+     * @param actionContext the action context
+     */
+    public static void loadParamByAnnotationAndPutToContext(@Nonnull final ParamType paramType, @Nonnull String paramName, Object paramValue,
+                                                            @Nonnull final BusinessActionContextParameter annotation, @Nonnull final Map<String, Object> actionContext) {
+        ActionContextUtil.loadParamByAnnotationAndPutToContext(paramType, paramName, paramValue, annotation, actionContext);
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java]: maybe  a circular call ?

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    }
+
+
+    public static String getParamNameFromAnnotation(@Nonnull BusinessActionContextParameter annotation) {
+        return ActionContextUtil.getParamNameFromAnnotation(annotation);
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java]: same above.

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        super(failureHandler, methodsToProxy, aspectTransactional);
+    }
+
+    @Override
+    protected Object doInvoke(InvocationWrapper invocation) throws Throwable {
+        Class<?> targetClass = invocation.getTarget().getClass();
+        Method specificMethod = ClassUtils.getMostSpecificMethod(invocation.getMethod(), targetClass);
+        if (specificMethod != null && !specificMethod.getDeclaringClass().equals(Object.class)) {
+            final GlobalTransactional globalTransactionalAnnotationOld = getAnnotation(specificMethod, targetClass, GlobalTransactional.class);
+            final org.apache.seata.spring.annotation.GlobalTransactional globalTransactionalAnnotationNew = getAnnotation(specificMethod, targetClass, org.apache.seata.spring.annotation.GlobalTransactional.class);
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java]: I think this handler should only serve `io.seata.xx`

Comment (xingfudeshi) [reply compatible/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java]: OK

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java (hunk 2 above)
Comment (xingfudeshi) [reply compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java]: Will fix it soon.

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+ * The type Global transactional interceptor handler.
+ */
+public class GlobalTransactionalInterceptorHandler extends org.apache.seata.integration.tx.api.interceptor.handler.GlobalTransactionalInterceptorHandler {
+
+
+    public GlobalTransactionalInterceptorHandler(FailureHandler failureHandler, Set<String> methodsToProxy) {
+        super(failureHandler, methodsToProxy);
+    }
+
+    public GlobalTransactionalInterceptorHandler(FailureHandler failureHandler, Set<String> methodsToProxy, AspectTransactional aspectTransactional) {
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java:41]: I think `FailureHandler` should belong to the io.seata.xx package. At the same time, `FailureHandler`  is also a user API that allows users to customize and load by the Spring bean.

File: compatible/src/main/java/io/seata/spring/annotation/GlobalTransactional.java [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+     * @return string [ ]
+     */
+    String[] noRollbackForClassName() default {};
+
+    /**
+     * the propagation of the global transaction
+     *
+     * @return propagation
+     */
+    Propagation propagation() default Propagation.REQUIRED;
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/spring/annotation/GlobalTransactional.java:84]: 'Propagation' should belong to the io.seata.xx package. If the user defines this parameter in the annotation parameter, 'Propagation' cannot be found because the location of the package changes.

File: compatible/src/main/java/io/seata/spring/annotation/GlobalTransactional.java [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+     * @return int
+     */
+    int lockRetryTimes() default -1;
+
+    /**
+     * pick the Acquire lock policy
+     *
+     * @return lock strategy mode
+     */
+    LockStrategyMode lockStrategyMode() default LockStrategyMode.PESSIMISTIC;
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/spring/annotation/GlobalTransactional.java:119]: same above.

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionInterceptorHandler.java [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+                    Object paramObject = arguments[i];
+                    if (paramObject == null) {
+                        continue;
+                    }
+
+                    // load param by the config of annotation, and then put into the context
+                    ActionContextUtil.loadParamByAnnotationAndPutToContext(ParamType.PARAM, "", paramObject, annotation, context);
+                } else if (parameterAnnotations[i][j] instanceof org.apache.seata.rm.tcc.api.BusinessActionContextParameter) {
+                    // get annotation
+                    org.apache.seata.rm.tcc.api.BusinessActionContextParameter annotation = (org.apache.seata.rm.tcc.api.BusinessActionContextParameter) parameterAnnotations[i][j];
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionInterceptorHandler.java]: I think just check `io.seata... annotation` here.  For `org.apache.seata.rm.tcc.api.BusinessActionContextParameter` should by the `org. apache. seata. Integration.tx. api.interceptor. ActionInterceptorHandler` to deal with, because here is override the parent method.

Comment (slievrly) [reply compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionInterceptorHandler.java]: our purpose is to ensure that the user use ` org.apache.seata.rm.tcc.api.BusinessActionContextParameter` and `io.seata.rm.tcc.api.BusinessActionContextParameter` these two APIs can be compatible. You can use inheritance or override on the implementation, but try not to cross each other. This ensures consistency of logic and maintainability of the code.

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java [hunk 8]
```diff
@@ -0,0 +1,170 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package io.seata.integration.tx.api.interceptor;
+
+import io.seata.rm.tcc.api.BusinessActionContextParameter;
+import org.apache.seata.common.util.CollectionUtils;
+import org.apache.seata.common.util.StringUtils;
+import org.apache.seata.rm.tcc.api.BusinessActionContext;
```
Comment (slievrly) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/ActionContextUtil.java]: It doesn't look like it's actually in use.

**Comment by xingfudeshi** [comment]
Ok.I got the point.Thank you!

**Comment by xingfudeshi** [comment]
Done. @slievrly

**Review by slievrly — APPROVED** [review]
LGTM

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/parser/GlobalTransactionalInterceptorParser.java [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+ */
+package io.seata.integration.tx.api.interceptor.parser;
+
+import io.seata.spring.annotation.GlobalLock;
+import io.seata.spring.annotation.GlobalTransactional;
+import org.apache.seata.common.util.CollectionUtils;
+
+import java.lang.reflect.Method;
+
+public class GlobalTransactionalInterceptorParser extends org.apache.seata.integration.tx.api.interceptor.parser.GlobalTransactionalInterceptorParser {
```
Comment (funky-eyes) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/parser/GlobalTransactionalInterceptorParser.java:25]: Why didn't I find the spi file for org.apache.seata.integration.tx.api.interceptor.parser?
为什么我没找到org.apache.seata.integration.tx.api.interceptor.parser的spi文件？

Comment (funky-eyes) [reply compatible/src/main/java/io/seata/integration/tx/api/interceptor/parser/GlobalTransactionalInterceptorParser.java:25]: meta-inf/service/org.apache.seata.integration.tx.api.interceptor.parser.InterfaceParser

File: compatible/src/main/java/io/seata/integration/tx/api/interceptor/parser/GlobalTransactionalInterceptorParser.java [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+                for (Method method : methods) {
+                    trxAnnoOld = method.getAnnotation(GlobalTransactional.class);
+                    trxAnnoNew = method.getAnnotation(org.apache.seata.spring.annotation.GlobalTransactional.class);
+                    if (trxAnnoOld != null || trxAnnoNew != null) {
+                        methodsToProxy.add(method.getName());
+                        result = true;
+                    }
+
+                    GlobalLock lockAnnoOld = method.getAnnotation(GlobalLock.class);
+                    org.apache.seata.spring.annotation.GlobalLock lockAnnoNew = method.getAnnotation(org.apache.seata.spring.annotation.GlobalLock.class);
```
Comment (funky-eyes) [inline compatible/src/main/java/io/seata/integration/tx/api/interceptor/parser/GlobalTransactionalInterceptorParser.java:51]: ibid
