### PR TITLE
bugfix: Enhance 401 Error Handling by Refreshing Token in acquireClusterMetaData Method

### LINKED ISSUE #6919: When the status code for Raft-related requests is 401, the refreshToken should be triggered as soon as possible.
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
RaftRegistryServiceImpl#acquireClusterMetaData & watch 中，对于出现401情况只进行了重试，但是重试并不代表会触发refreshToken，而绝大多数401来源于token过期，所以应该尽快的重新获取token
In RaftRegistryServiceImpl#acquireClusterMetaData and watch, when a 401 status occurs, only a retry is performed. However, a retry does not necessarily trigger a refreshToken, and the majority of 401 errors stem from token expiration. Therefore, the token should be re-acquired as soon as possible.
```
    private static void acquireClusterMetaData(String clusterName, String group) throws RetryableException {
        String tcAddress = queryHttpAddress(clusterName, group);
        Map<String, String> header = new HashMap<>();
        header.put(HTTP.CONTENT_TYPE, ContentType.APPLICATION_FORM_URLENCODED.getMimeType());
        if (isTokenExpired()) {
            refreshToken(tcAddress);
        }
        if (StringUtils.isNotBlank(jwtToken)) {
            header.put(AUTHORIZATION_HEADER, jwtToken);
        }
        if (StringUtils.isNotBlank(tcAddress)) {
            Map<String, String> param = new HashMap<>();
            param.put("group", group);
            String response = null;
            try (CloseableHttpResponse httpResponse =
                HttpClientUtil.doGet("http://" + tcAddress + "/metadata/v1/cluster", param, header, 1000)) {
                if (httpResponse != null) {
                    if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_OK) {
                        response = EntityUtils.toString(httpResponse.getEntity(), StandardCharsets.UTF_8);
                    } else if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_UNAUTHORIZED) {
                        if (StringUtils.isNotBlank(USERNAME) && StringUtils.isNotBlank(PASSWORD)) {
                            throw new RetryableException("Authentication failed!");
                        } else {
                            throw new AuthenticationFailedException("Authentication failed! you should configure the correct username and password.");
                        }
                    }
                }
                MetadataResponse metadataResponse;
                if (StringUtils.isNotBlank(response)) {
                    try {
                        metadataResponse = OBJECT_MAPPER.readValue(response, MetadataResponse.class);
                        METADATA.refreshMetadata(clusterName, metadataResponse);
                    } catch (JsonProcessingException e) {
                        LOGGER.error(e.getMessage(), e);
                    }
                }
            } catch (IOException e) {
                throw new RetryableException(e.getMessage(), e);
            }
        }
    }
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by o-jimin**
…thod

- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
This pull request modifies the acquireClusterMetaData method in the RaftRegistryServiceImpl class to improve the handling of 401 Unauthorized errors. When a 401 error occurs during metadata retrieval, the code now attempts to refresh the authentication token and retry the request with the new token. This enhancement ensures that the application can recover from token expiration without manual intervention, thus improving user experience and system reliability.

### Ⅱ. Does this pull request fix one issue?

fixes #6919

### CODE REVIEW

File: discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java [hunk 1]
```diff
@@ -377,14 +377,23 @@ private static void acquireClusterMetaData(String clusterName, String group) thr
...
+                    if (statusCode == HttpStatus.SC_OK) {
                         response = EntityUtils.toString(httpResponse.getEntity(), StandardCharsets.UTF_8);
-                    } else if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_UNAUTHORIZED) {
-                        if (StringUtils.isNotBlank(USERNAME) && StringUtils.isNotBlank(PASSWORD)) {
-                            throw new RetryableException("Authentication failed!");
+                    } else if (statusCode == HttpStatus.SC_UNAUTHORIZED) {
+                        refreshToken(tcAddress);
+
+                        header.put(AUTHORIZATION_HEADER, jwtToken);
+                        httpResponse = HttpClientUtil.doGet("http://" + tcAddress + "/metadata/v1/cluster", param, header, 1000);
```
Comment (funky-eyes) [inline discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: I believe that simply refreshing the token is sufficient, and there is no need to retry the request, as the RetryableException will automatically retry after one second when it is thrown.

Comment (o-jimin) [reply discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: yes i fixed

**Comment by funky-eyes** [comment]
https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md
https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md
请在上述md文件中登记pr信息和作者信息
Please register pr information and author information in the above md file

**Comment by o-jimin** [comment]
yes I have written it

File: discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java [hunk 2]
```diff
@@ -377,14 +377,14 @@ private static void acquireClusterMetaData(String clusterName, String group) thr
...
+                    if (statusCode == HttpStatus.SC_OK) {
                         response = EntityUtils.toString(httpResponse.getEntity(), StandardCharsets.UTF_8);
-                    } else if (httpResponse.getStatusLine().getStatusCode() == HttpStatus.SC_UNAUTHORIZED) {
-                        if (StringUtils.isNotBlank(USERNAME) && StringUtils.isNotBlank(PASSWORD)) {
-                            throw new RetryableException("Authentication failed!");
-                        } else {
-                            throw new AuthenticationFailedException("Authentication failed! you should configure the correct username and password.");
-                        }
+                    } else if (statusCode == HttpStatus.SC_UNAUTHORIZED) {
+                        refreshToken(tcAddress);
```
Comment (funky-eyes) [inline discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: why remove 
`(StringUtils.isNotBlank(USERNAME) && StringUtils.isNotBlank(PASSWORD)`

Comment (o-jimin) [reply discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: I thought it wasn't necessary, but having validation might be good, so I made the changes.

Comment (funky-eyes) [reply discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: > I thought it wasn't necessary, but having validation might be good, so I made the changes.

I think refreshToken(tcAddress); should be placed after the condition check; otherwise, it will waste a call when the account password is empty

Comment (o-jimin) [reply discovery/seata-discovery-raft/src/main/java/org/apache/seata/discovery/registry/raft/RaftRegistryServiceImpl.java]: I initially placed it outside the condition because refreshToken checks the account, but your point makes sense, so I moved it. Thanks for the feedback!

**Review by funky-eyes — APPROVED** [review]
LGTM

**Comment by injae-kim** [comment]
Nice work @o-jimin !!
