### PR TITLE
optimize: Add empty push protection for Configuration

### LINKED ISSUE #7564: Add empty push protection for NacosConfiguration
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [ ] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

https://github.com/apache/incubator-seata/blob/2.x/config/seata-config-nacos/src/main/java/org/apache/seata/config/nacos/NacosConfiguration.java#L445
When Nacos pushes an empty configuration, it will overwrite the current cached configuration. If a user accidentally deletes the configuration content, or if there are compatibility issues between different Nacos versions that result in lost configuration content, Seata may fail to retrieve information such as the transaction group, which can lead to system failures.

### Ⅱ. Describe what happened

_No response_

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

_No response_

### PR DESCRIPTION
**Pull request by YvCeung**
- [x] I have read the [CONTRIBUTING.md](https://github.com/apache/incubator-seata/blob/2.x/CONTRIBUTING.md) guidelines.
- [x] I have registered the PR [changes](https://github.com/apache/incubator-seata/tree/2.x/changes).

### Ⅰ. Describe what this PR did
The configuration centers that Seata interfaces with, such as Nacos, will update the local configuration upon receiving a request for configuration changes. However, Nacos may mistakenly push null values, causing the local configuration to be cleared and thereby affecting business operations. Protective measures need to be taken for this situation

### Ⅱ. Does this pull request fix one issue?

fix #7564 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 
```shell
mvn clean test
```

### CODE REVIEW

**Review by YongGoose — CHANGES_REQUESTED** [review]
It would be good to add a test to verify that the logs are being output correctly.

**Comment by YvCeung** [comment]
@funky-eyes PTAL

**Review by funky-eyes — APPROVED** [review]
LGTM
@YongGoose PTAL

File: config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java [hunk 1]
```diff
@@ -131,6 +133,31 @@ void testInitSeataConfig() throws Exception {
...
+        when(mockConsulClient.getKVValue(eq(dataId), isNull(), any(QueryParams.class)))
+                .thenReturn(blankResponse);
+
+        // Run onChangeEvent in a separate thread since it loops indefinitely
+        Thread thread = new Thread(() -> listener.onChangeEvent(new ConfigurationChangeEvent()));
+        thread.start();
+        Thread.sleep(100);
+        // Interrupt to break the loop
+        thread.interrupt();
+        thread.join(500);
```
Comment (YongGoose) [inline config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: What is the purpose of this code?

Comment (YvCeung) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: image
Since this change event of Consul is executed in a continuous loop, if the current thread is not interrupted, the single test will never end. Our goal is to verify the business logic, so we give it 100ms to execute and then interrupt it

Comment (YongGoose) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: But if it's `blank`, doesn't the `return` statement make it exit the while loop?

Comment (YvCeung) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: > But if it's `blank`, doesn't the `return` statement make it exit the while loop?

Yes, you're right. However, here "return" should be changed to "continue". In fact, long polling should not be exited

Comment (YongGoose) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: I also see `return` statements in other configuration code.
And please don’t close the conversation while it’s still ongoing.

Comment (YvCeung) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: > I also see `return` statements in other configuration code. And please don’t close the conversation while it’s still ongoing.

That's because other configuration types passively receive change push notifications. If an empty configuration is received, just return it directly. consul, on the other hand, requires the client to continuously undergo long-term training (active acquisition) at regular intervals.

Comment (YongGoose) [reply config/seata-config-consul/src/test/java/org/apache/seata/config/consul/ConsulConfigurationTest.java:155]: Ok, I understand
Thank you for your explanation :)

**Review by YongGoose — APPROVED** [review]
LGTM
