### PR TITLE
bugfix: Github Action workflow does not run the corresponding Kotlin test

### LINKED ISSUE #7469: TransactionScopeTest cannot run normally and throws an exception
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description

When running the test `TransactionScopeTest`, I found that the original test could not run properly and assertion errors would occur.

A more detailed location is in `testGlobalTransactional()`. When running this method, an assertion error occurs.

### Ⅱ. Describe what happened

Stack Trace:

```
org.opentest4j.AssertionFailedError: expected: not <null>

	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:47)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:36)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:31)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:300)
	at org.apache.seata.spring.kt.TransactionScopeTest.testGlobalTransactional(TransactionScopeTest.kt:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

JDK17
Module: spring.kt
Test class: TransactionScopeTest

### PR DESCRIPTION
**Pull request by maple525866**
- [x] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
Add Kotlin test compilation configuration in pom.xml of Spring module

Refactored and fixed the logic of TransactionScopeTest to avoid polluting other tests in Github Action
### Ⅱ. Does this pull request fix one issue?

fixes: #7469 

### Ⅳ. Describe how to verify it
./mvnw clean compile test-compile -pl spring

./mvnw test -pl spring

Successfully detected TransactionScopeTest error
image

### CODE REVIEW

**Comment by maple525866** [comment]
Now the test problem has been exposed

https://github.com/apache/incubator-seata/actions/runs/15928884754/job/44932859979?pr=7482#step:9:11353

**Comment by maple525866** [comment]
PTAL @YongGoose @funky-eyes

**Comment by YongGoose** [comment]
First, we should probably focus on resolving the current error.

```
org.apache.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.test-tx-group configuration item is required
```

We’ll need to check whether compiling the test code caused some previously unexecuted tests to run, or if the issue was introduced directly by the compilation process itself.

**Comment by maple525866** [comment]
> 首先，我们应该集中精力解决当前的错误。
> 
> ```
> org.apache.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.test-tx-group configuration item is required
> ```
> 
> 我们需要检查编译测试代码是否导致一些以前未执行的测试运行，或者问题是否是由编译过程本身直接引入的。

The problem doesn't seem to be easy to solve...

**Comment by maple525866** [comment]
> > 首先，我们应该集中精力解决当前的错误。
> > ```
> > org.apache.seata.config.exception.ConfigNotFoundException: service.vgroupMapping.test-tx-group configuration item is required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我们需要检查编译测试代码是否导致一些以前未执行的测试运行，或者问题是否是由编译过程本身直接引入的。
> 
> 这个问题似乎不容易解决……

I seem to have found one of the causes of the problem. Since TransactionScopeTest itself has problems after testing, I first checked the cause of the error. After research, I found that RootContext.bind(DEFAULT_XID) was set in TransactionScopeTest, but it was not cleaned up correctly, which may cause subsequent tests (such as MethodDescTest.testGlobalTransactional) to be affected.

I summarized two reasons for the error, which may be useful for reference:

1. GitHub Actions may use different test discovery and execution order, so it is different from the situation of local testing

2. Some tests did not properly clean up the global state (such as RootContext) and the state pollution between tests

**Comment by YongGoose** [comment]
> * GitHub Actions may use different test discovery and execution order, so it is different from the situation of local testing
> *

That’s right. In GitHub Actions, the test execution order can differ from local environments, so test isolation is important.
With that in mind, would it be possible to make that test independent from others?

To summarize — can we make it work reliably regardless of the execution order?

**Comment by maple525866** [comment]
> > * GitHub Actions 可能使用不同的测试发现和执行顺序，因此与本地测试的情况不同
> 
> 没错。在 GitHub Actions 中，测试执行顺序可能与本地环境不同，因此测试隔离非常重要。 考虑到这一点，是否可以使该测试独立于其他测试？
> 
> 总结一下——无论执行顺序如何，我们能否让它可靠地工作？

I tried to isolate `TransactionScopeTest` from other tests and refactored it to fix the logic of the original test and improve the original test coverage

**Comment by maple525866** [comment]
What do you think of the current changes? ❤️@YongGoose

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt [hunk 1]
```diff
@@ -49,16 +56,19 @@ class TransactionScopeTest {
                 name: String,
                 timeout: Int
             ): String {
+                println("Mock TransactionManager.begin() called, returning: $DEFAULT_XID")
```
Comment (YongGoose) [inline spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: Using `System.out.println` can degrade performance.
Therefore, I believe it’s inappropriate to use it in methods that run repeatedly, such as those annotated with `@BeforeEach`!

What do you think?

image

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt [hunk 2]
```diff
@@ -72,62 +82,220 @@ class TransactionScopeTest {
...
+    fun tearDown() {
+        // Clean up global state to avoid affecting other tests
+        RootContext.unbind()
+        
+        // Restore original TransactionManager
+        backupTransactionManager?.let { TransactionManagerHolder.set(it) }
+    }
+
+    @Test
+    @Throws(NoSuchMethodException::class)
```
Comment (YongGoose) [inline spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:130]: Just wondering — what’s the purpose of this annotation?

**Review by YongGoose — COMMENTED** [review]
Leaving comments in tests is a good practice!!

However, I think using `Javadoc` might improve readability even more.
So I’d recommend documenting them with `Javadoc` instead — what do you think?

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 2 above)
Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:130]: we need to inform the Java compiler that this method may throw a NoSuchMethodException

In this test method, it may involve:

1. Reflection operation: Get method and annotation information

2. Spring AOP proxy: Access the method of the proxy object

3. Annotation processing: Process the @GlobalTransactional annotation

All these operations may throw a NoSuchMethodException, so use @Throws to declare.

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 1 above)
Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: This was just to make it easier for me to test the refactored method and observe if there are any vulnerabilities. It has now been removed.❤️

**Comment by YongGoose** [comment]
> Leaving comments in tests is a good practice!!
> 
> However, I think using `Javadoc` might improve readability even more. So I’d recommend documenting them with `Javadoc` instead — what do you think?

@maple525866 

What do you think about this approach? 🤔

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt [hunk 3]
```diff
@@ -72,62 +78,215 @@ class TransactionScopeTest {
...
+                // Clean up
+                RootContext.unbind()
+            }
+            
+            // Verify that transaction context can be propagated in coroutines
+            Assertions.assertNotNull(capturedXid, "TransactionCoroutineContext should propagate transaction context")
+            Assertions.assertEquals(DEFAULT_XID, capturedXid)
+        } catch (e: Exception) {
+            throw e
         }
```
[the remark this answers is not in the document]
Comment (YongGoose) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: Seems reasonable!

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt [hunk 4]
```diff
@@ -72,62 +78,215 @@ class TransactionScopeTest {
...
+        try {
+            var capturedXid: String? = null
+            
+            // Simulate transactionScope behavior with simplified logic
+            runBlocking {
+                // Manually bind an XID to simulate transaction start
+                RootContext.bind(DEFAULT_XID)
+                
+                // Propagate transaction in coroutine context
+                withContext(org.apache.seata.spring.kt.support.TransactionCoroutineContext()) {
```
[the remark this answers is not in the document]
Comment (YongGoose) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: ditto

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 3 above)
[the remark this answers is not in the document]
Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: done❤️

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 4 above)
[the remark this answers is not in the document]
Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: done❤️

**Comment by maple525866** [comment]
> > 在测试中留下评论是一种很好的做法！！
> > 不过，我认为使用`Javadoc`可能会更能提高可读性。所以我建议用 来记录它们`Javadoc`——你觉得呢？
> 
> @maple525866
> 
> 你觉得这个方法怎么样？🤔

done❤️

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt [hunk 5]
```diff
@@ -72,63 +94,236 @@ class TransactionScopeTest {
...
+     * Cleans up the test environment after each test method.
+     * 
+     * This method:
+     * - Unbinds any remaining transaction context
+     * - Restores the original TransactionManager
+     */
+    @AfterEach
+    fun tearDown() {
+        // Clean up global state to avoid affecting other tests
+        RootContext.unbind()
```
Comment (YongGoose) [inline spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: If RootContext is cleared in `@BeforeEach`, wouldn’t it be unnecessary to do it again in `@AfterEach`?

**Review by YongGoose — COMMENTED** [review]
Sorry for the late reply

I think we're almost there!!
Also, Please resolve the conflicts in 2.x files

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 5 above)
Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: done❤️

Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt]: > @BeforeEach

But I think adding RootContext.unbind() in @AfterEach may prevent other tests from being polluted (double protection with @BeforeEach), what do you think?

Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: > If RootContext is cleared in `@BeforeEach`, wouldn’t it be unnecessary to do it again in `@AfterEach`?

But I think adding RootContext.unbind() in @AfterEach may prevent other tests from being polluted (double protection with @BeforeEach), what do you think?

Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: > > If RootContext is cleared in `@BeforeEach`, wouldn’t it be unnecessary to do it again in `@AfterEach`?
> 
> But I think adding RootContext.unbind() in @AfterEach may prevent other tests from being polluted (double protection with @beforeeach), what do you think?

But after the changes, the workflow seems to be running normally, which may mean that I am worrying too much.

File: spring/pom.xml [hunk 6]
```diff
@@ -131,6 +131,14 @@
                             <goal>compile</goal>
                         </goals>
                     </execution>
+                    <!-- Add this execution to compile the test code -->
+                    <execution>
+                        <id>test-compile</id>
+                        <phase>process-test-sources</phase>
```
[the remark this answers is not in the document]
Comment (maple525866) [reply spring/pom.xml]: you are right

File: spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt (hunk 5 above)
Comment (YongGoose) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: From the perspective of double protection, I think it's fine to have both applied.
I gave it a bit more thought, and if we only annotate `@BeforeEach`, there's a chance that `RootContext.unbind` might not be called after the very last test.

I'll leave it up to your judgment!

Comment (maple525866) [reply spring/src/test/java/org/apache/seata/spring/kt/TransactionScopeTest.kt:112]: > From the perspective of double protection, I think it's fine to have both applied. I gave it a bit more thought, and if we only annotate `@BeforeEach`, there's a chance that `RootContext.unbind` might not be called after the very last test.
> 
> I'll leave it up to your judgment!

I personally prefer to add `RootContext.unbind()` in `@AfterEach`

**Review by YongGoose — APPROVED** [review]
LGTM 🚀

**Comment by maple525866** [comment]
> LGTM🚀

Thank you for your time and attention

**Review by funky-eyes — APPROVED** [review]
LGTM
