### PR TITLE
bugfix: undolog rollback info more than 64MB

### LINKED ISSUE #6451: Undolog Packet for query is too large when table longblob field more than 40MB
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
Packet for query is too large (83,886,137 > 67,108,864). You can change this value on the server by setting the 'max_allowed_packet' variable.

```
create table test (
id int primary key,
name varchar(45),
file longblob
)
```

```
insert into test(id, name file) values(1, 'name', '<binary 40MB>');
```

```
update test set file = '<binary 40MB>', name = 'name2' where id = 1;
```

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by jsbxyyx**
- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #6451

### CODE REVIEW

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/DataSourceProxy.java [hunk 1]
```diff
@@ -399,27 +403,36 @@ public String getKernelVersion() {
...
-                }
-                int dashIdx = version.indexOf('-');
-                // in mysql: 5.6.45, in polardb-x: 5.6.45-TDDL-xxx
-                if (dashIdx > 0) {
-                    kernelVersion = version.substring(0, dashIdx);
-                    productVersion = version.substring(dashIdx + 1);
-                } else {
-                    kernelVersion = version;
-                    productVersion = version;
+        try (PreparedStatement preparedStatement = connection.prepareStatement("SHOW VARIABLES");
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/DataSourceProxy.java:414]: 是不是应该弄一个variables的元数据存储的类，否则都放在datasourceproxy里，有点臃肿
Should I get a metadata storage class for variables, otherwise it will be put in datasourceproxy, which is a bit bloated?

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java [hunk 2]
```diff
@@ -49,6 +62,8 @@ public class MySQLUndoLogManager extends AbstractUndoLogManager {
     private static final String DELETE_UNDO_LOG_BY_CREATE_SQL = "DELETE FROM " + UNDO_LOG_TABLE_NAME +
             " WHERE " + ClientTableColumnsName.UNDO_LOG_LOG_CREATED + " <= ? LIMIT ?";
 
+    private static final IdWorker ID_WORKER = new IdWorker(null);
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java]:
```suggestion
```

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java [hunk 3]
```diff
@@ -67,10 +82,89 @@ public int deleteUndoLogByLogCreated(Date logCreated, int limitRows, Connection
...
+            byte[] first = new byte[limit];
+            StringBuilder subIdBuilder = new StringBuilder(36);
+            while (pos < undoLogContent.length) {
+                if (pos == 0) {
+                    System.arraycopy(undoLogContent, pos, first, 0, first.length);
+                    pos += first.length;
+                } else {
+                    byte[] bytes = new byte[Math.min(undoLogContent.length - pos, limit)];
+                    System.arraycopy(undoLogContent, pos, bytes, 0, bytes.length);
+                    long subId = ID_WORKER.nextId();
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java]: 使用UUIDGenerator，将其移动到common模块
Use UUIDGenerator to move it to a common module

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java [hunk 4]
```diff
@@ -151,18 +161,28 @@ public void batchDeleteUndoLog(Set<String> xids, Set<Long> branchIds, Connection
         int xidSize = xids.size();
         int branchIdSize = branchIds.size();
         String batchDeleteSql = toBatchDeleteUndoLogSql(xidSize, branchIdSize);
-        try (PreparedStatement deletePST = conn.prepareStatement(batchDeleteSql)) {
+        String batchDeleteSubSql = toBatchDeleteSubUndoLogSql(xidSize, branchIdSize);
+        try (PreparedStatement deletePST = conn.prepareStatement(batchDeleteSql);
+             PreparedStatement deleteSubPST = conn.prepareStatement(batchDeleteSubSql)) {
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java:167]: 为什么不在上面的batch delete sql中直接增加删除sub的条件？
Why not add the condition to delete sub directly in the batch delete sql above?

Comment (jsbxyyx) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java:167]: 主log和子log的条件不一样

The conditions for the main log and the sub-log are different.

File: common/src/test/resources/io/TestFile.txt [hunk 5]
```diff
@@ -1,3 +1,20 @@
+====
```
Comment (l81893521) [inline common/src/test/resources/io/TestFile.txt]: Fix the code conflict

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java (hunk 4 above)
Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java:167]: > 主log和子log的条件不一样
> 
> The conditions for the main log and the sub-log are different.

为什么我们不能将其合并成一个sql？虽然条件不一样，可以是or的关系不是吗？
Why can't we merge it into one sql? Although the conditions are different, it can be an or relationship, right?

Comment (jsbxyyx) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java:167]: 一个是走索引，一个不走索引的
One is indexed, and the other is not indexed.

Comment (funky-eyes) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java:167]: ok

**Review by funky-eyes — APPROVED** [review]
LGTM

File: .asf.yaml [hunk 6]
```diff
@@ -14,6 +14,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
+
```
Comment (funky-eyes) [inline .asf.yaml]:
```suggestion
```
