### PR TITLE
bugfix: treating a unique index conflict during rollback as a dirty write

### LINKED ISSUE #6561: when doing global rollback ,may cause an endless loop
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
if there is a table like 
`
CREATE TABLE `t_test` (
  `urid` int NOT NULL,
  `name` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`urid`),
  UNIQUE KEY `t_test_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
`
name is a uniquekey.  and There is a piece of data in the table. (1,1)
1、global Transaction execute the sql "delete from t_test where id = 1", and this transaction need rollback
2、when rollbacking,other thread execute a sql like "insert into t_test values (2,1)"
3、that will cause the rollback thread  endless loop.

### Ⅱ. Describe what happened
that's because the range of the code "catch (SQLIntegrityConstraintViolationException e)" is too wide  in AbstractUndoLogManager#undo
and rollback of business will be catched by this.
that should just catch "insertUndoLogWithGlobalFinished"

- JDK version(e.g. `java -version`):
- Seata client/server version:  1.6.X
- Database version: mysql 8.X
- OS(e.g. `uname -a`): centos7
- Others: jdk8

### PR DESCRIPTION
**Pull request by YongGoose**
- [x] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #6561

### CODE REVIEW

File: rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java [hunk 1]
```diff
@@ -400,6 +400,8 @@ public void undo(DataSourceProxy dataSourceProxy, String xid, long branchId) thr
                 if (LOGGER.isInfoEnabled()) {
                     LOGGER.info("xid {} branch {}, undo_log inserted, retry rollback", xid, branchId);
                 }
+                throw new BranchTransactionException(BranchRollbackFailed_Unretriable, String.format(
```
Comment (funky-eyes) [inline rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java]: It should not be written here; the exception handling should be done in `undoExecutor.executeOn`

Comment (YongGoose) [reply rm-datasource/src/main/java/org/apache/seata/rm/datasource/undo/AbstractUndoLogManager.java]: Done in https://github.com/apache/incubator-seata/pull/7135/commits/45a151d6ab614d9e0c52866ac19a7d33a4dbf40c !

PTAL 🙂

**Review by funky-eyes — COMMENTED** [review]
Please register your PR in those two files :
https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md
https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md

**Comment by YongGoose** [comment]
> Please register your PR in those two files : https://github.com/apache/incubator-seata/blob/2.x/changes/zh-cn/2.x.md https://github.com/apache/incubator-seata/blob/2.x/changes/en-us/2.x.md

Done in https://github.com/apache/incubator-seata/pull/7135/commits/fb2eaf200f526f96ca9cb804f4f50120a242ba6a !

Please check if the Chinese translation is correct.

File: changes/en-us/2.x.md [hunk 2]
```diff
@@ -17,6 +17,7 @@ Add changes here for all PR submitted to the 2.x branch.
 - [[#7112](https://github.com/apache/incubator-seata/pull/7112)] bugfix: remove the condition that IPv6 must start with fe80
 - [[#7107](https://github.com/apache/incubator-seata/pull/7107)] fix the issue of failing to parse annotations in TCC mode when the business object is a proxy object.
 - [[#7124](https://github.com/apache/incubator-seata/pull/7124)] bugfix: GlobalTransactionScanner.afterPropertiesSet need do scanner check
+- [[#7135](https://github.com/apache/incubator-seata/pull/7135)] catch SQLIntegrityConstraintViolationException and handle rollback
```
Comment (funky-eyes) [inline changes/en-us/2.x.md]:
```suggestion
- [[#7135](https://github.com/apache/incubator-seata/pull/7135)] treating a unique index conflict during rollback as a dirty write
```

File: changes/zh-cn/2.x.md [hunk 3]
```diff
@@ -17,6 +17,7 @@
 - [[#7112](https://github.com/apache/incubator-seata/pull/7112)] 校验是否IPv6网络ip取消必须以fe80开始的条件
 - [[#7107](https://github.com/apache/incubator-seata/pull/7107)] 修复tcc模式下，当业务对象为代理对象时，解析注解失败问题。
 - [[#7124](https://github.com/apache/incubator-seata/pull/7124)] GlobalTransactionScanner.afterPropertiesSet方法需要做扫描检查
+- [[#7135](https://github.com/apache/incubator-seata/pull/7135)] 修复捕获 SQLIntegrityConstraintViolationException 并处理回滚的问题
```
Comment (funky-eyes) [inline changes/zh-cn/2.x.md]:
```suggestion
- [[#7135](https://github.com/apache/incubator-seata/pull/7135)] 回滚时遇到唯一索引冲突视为脏写
```

File: changes/en-us/2.x.md (hunk 2 above)
Comment (YongGoose) [reply changes/en-us/2.x.md]: Thank you. 

Documentation work always feels difficult.
Especially, coming up with names is even harder. 🥲

File: changes/en-us/2.x.md
Comment (funky-eyes) [inline changes/en-us/2.x.md:1]: Please make sure your Github ID is in the list below

File: changes/zh-cn/2.x.md
Comment (funky-eyes) [inline changes/zh-cn/2.x.md:1]: Please make sure your Github ID is in the list below

File: changes/en-us/2.x.md
Comment (YongGoose) [reply changes/en-us/2.x.md:1]: Good catch!

Done it https://github.com/apache/incubator-seata/pull/7135/commits/196f2182020dab4212ef5e1776dbcf8b6cf38a1a !

**Review by funky-eyes — APPROVED** [review]
LGTM
