### PR TITLE
test: fix port of mock server

### LINKED ISSUE #7539: Port of mock server should be different from seata-server
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [x] I am willing to try to implement this feature myself.

### Why you need it?

Port of mock server should be different from seata-server

### How it could be?

_No response_

### Other related information

_No response_

### PR DESCRIPTION
**Pull request by Bughue**
- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes https://github.com/apache/incubator-seata/issues/7539

### CODE REVIEW

File: mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java [hunk 1]
```diff
@@ -59,7 +58,7 @@ public class MockServer {
     public static void main(String[] args) {
         SpringApplication.run(MockServer.class, args);
 
-        int port = NumberUtils.toInt(System.getenv(ENV_SEATA_PORT_KEY), DEFAULT_PORT);
+        int port = NumberUtils.toInt(System.getenv(MOCK_SEATA_PORT_KEY), MOCK_DEFAULT_PORT);
```
Comment (slievrly) [inline mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java:60]: Can the port be specified by passing in parameters? If there are two mock-servers running in the test, port conflicts will also occur.

Comment (Bughue) [reply mock-server/src/main/java/org/apache/seata/mockserver/MockServer.java:60]: done

**Comment by xjlgod** [comment]
should we add change docs?

**Comment by Bughue** [comment]
> should we add change docs?

done

File: changes/en-us/2.x.md [hunk 2]
```diff
@@ -39,6 +39,7 @@ Add changes here for all PR submitted to the 2.x branch.
 ### test:
 
 - [[#7541](https://github.com/seata/seata/pull/7541)] fix jakarta UT failed in jdk17+
+- [[#7541](https://github.com/seata/seata/pull/7540)] fix port of mock server
```
Comment (slievrly) [inline changes/en-us/2.x.md]: 7541 -> 7540

Comment (Bughue) [reply changes/en-us/2.x.md]: 改了

**Review by slievrly — APPROVED** [review]
LGTM
