### PR TITLE
optimize: remove fst serialization

### LINKED ISSUE #5999: [Proposal] remove low-security serializers that are no longer maintained
- [ ] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

### Ⅰ. Issue Description
fst and hessian are no longer maintained and do not support jdk17 and above, which is a huge problem for our future maintenance and security, I propose to remove these two serialization extensions on the 2.x branch

### Ⅱ. Describe what happened

  If there is an exception, please attach the exception trace:

```
Just paste your stack trace here!
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. xxx
2. xxx
3. xxx

Minimal yet complete reproducer code (or URL to code):

### Ⅵ. Environment:

- JDK version(e.g. `java -version`):
- Seata client/server version:  
- Database version:
- OS(e.g. `uname -a`):
- Others:

### PR DESCRIPTION
**Pull request by funky-eyes**
- [ ] I have registered the PR [changes](../changes).

### Ⅱ. Does this pull request fix one issue?

fixes #5999

### CODE REVIEW

File: core/src/main/java/io/seata/core/serializer/SerializerType.java [hunk 1]
```diff
@@ -43,13 +43,6 @@ public enum SerializerType {
      */
     KRYO((byte)0x4),
 
-    /**
-     * The fst.
-     * <p>
-     * Math.pow(2, 3)
-     */
-    FST((byte)0x8),
```
Comment (leizhiyuan) [inline core/src/main/java/io/seata/core/serializer/SerializerType.java]: Consider whether this enumeration type does not need to be removed or add a line of comments here to prevent future developers from reusing deprecated code when expanding the serialization protocol. However, in situations where some user clients have not been upgraded, code conflicts may arise, leading to unexpected problems.

考虑一下，是不是这个枚举类型无需移除，或者在这里加一行注释，防止后续的开发者，再扩展序列化协议的时候，复用了废弃的code，但是部分用户客户端还没有升级的情况下，code冲突，出现预期外的问题

Comment (funky-eyes) [reply core/src/main/java/io/seata/core/serializer/SerializerType.java]: > Consider whether this enumeration type does not need to be removed or add a line of comments here to prevent future developers from reusing deprecated code when expanding the serialization protocol. However, in situations where some user clients have not been upgraded, code conflicts may arise, leading to unexpected problems.
> 
> 考虑一下，是不是这个枚举类型无需移除，或者在这里加一行注释，防止后续的开发者，再扩展序列化协议的时候，复用了废弃的code，但是部分用户客户端还没有升级的情况下，code冲突，出现预期外的问题

Good point. That's a better way to handle it.

Comment (funky-eyes) [reply core/src/main/java/io/seata/core/serializer/SerializerType.java]: done

**Review by slievrly — APPROVED** [review]
LGTM
