### PR TITLE
bugfix: mvn spotless:apply failed

### LINKED ISSUE #7640: mvn spotless:apply failed
### Check Ahead

- [x] I have searched the [issues](https://github.com/seata/seata/issues) of this repository and believe that this is not a duplicate.

- [ ] I am willing to try to fix this bug myself.

### Ⅰ. Issue Description

`[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:apply (default-cli) on project seata-common: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:apply failed: An API incompatibility was encountered while executing com.diffplug.spotless:spotless-maven-plugin:2.44.3:apply: java.lang.NoSuchMethodError: 'java.util.Queue com.sun.tools.javac.util.Log$DeferredDiagnosticHandler.getDiagnostics()'`

Image

https://github.com/diffplug/spotless/issues/2468

`<palantirJavaFormat.version>2.71.0</palantirJavaFormat.version>`
palantirJavaFormat needs to be upgraded to version 2.71.0 or later.

### Ⅱ. Describe what happened

_No response_

### Ⅲ. Describe what you expected to happen

_No response_

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

_No response_

### Ⅴ. Anything else we need to know?

_No response_

### Ⅵ. Environment

- JDK version: 25

### PR DESCRIPTION
**Pull request by JongminChung**
- [x] I have read the [CONTRIBUTING.md](https://github.com/apache/incubator-seata/blob/2.x/CONTRIBUTING.md) guidelines.
- [x] I have registered the PR [changes](https://github.com/apache/incubator-seata/tree/2.x/changes).

### Ⅱ. Does this pull request fix one issue?

fixes: #7640 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

Just Maven Spoltess applied

### Ⅳ. Describe how to verify it

image

### CODE REVIEW

**Comment by JongminChung** [comment]
Hi. @xingfudeshi

Thank you for changing the Chinese phrase.

**Comment by xingfudeshi** [comment]
> Hi. @xingfudeshi
> 
> Thank you for changing the Chinese phrase.

No worries.

File: tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java [hunk 1]
```diff
@@ -290,7 +290,7 @@ private void rollbackTransaction(GlobalTransaction tx, Throwable originalExcepti
                 break;
             case TimeoutRollbacked:
             case Rollbacked:
-                // rollback transactions but do not exist are usually considered completed
+            // rollback transactions but do not exist are usually considered completed
```
Comment (JongminChung) [inline tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java:422]: In Java 11, this comment should be indented, but not indented in Java17, Java25, which is a problem.

Comment (funky-eyes) [reply tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java:422]: > In Java 11, this comment should be indented, but not indented in Java17, Java25, which is a problem.

Yes — with your current changes, everything for Java11 and above should now follow the same coding style, right?

Comment (JongminChung) [reply tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java:422]: ### Java 11 (Has Error ❌)
```shell
$ sdk use java 11.0.27-librca 
$  ./mvnw spotless:check 

[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:check (default-cli) on project seata-tm: The following files had format violations:
[ERROR]     src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java
[ERROR]         @@ -290,7 +290,7 @@
[ERROR]          ················break;
[ERROR]          ············case·TimeoutRollbacked:
[ERROR]          ············case·Rollbacked:
[ERROR]         -············//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
[ERROR]         +················//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
[ERROR]          ············case·Finished:
[ERROR]          ················code·=·TransactionalExecutor.Code.RollbackDone;
[ERROR]          ················break;
[ERROR] Run 'mvn spotless:apply' to fix these violations.
```

### Java 17 and above (✅)

```shell
$ sdk use java 17.0.16-librca (java 21, java 25 OK)
$  ./mvnw spotless:check 

[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:check (default-cli) on project seata-tm: The following files had format violations:
[ERROR]     src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java
[ERROR]         @@ -290,7 +290,7 @@
[ERROR]          ················break;
[ERROR]          ············case·TimeoutRollbacked:
[ERROR]          ············case·Rollbacked:
[ERROR]         -················//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
[ERROR]         +············//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
[ERROR]          ············case·Finished:
[ERROR]          ················code·=·TransactionalExecutor.Code.RollbackDone;
[ERROR]          ················break;
[ERROR] Run 'mvn spotless:apply' to fix these violations.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :seata-tm
```

This is the situation above, so there's no problem starting with Java 17 or later.

I have a problem with Java 11. And this happens unconditionally because the position of the comment changes.

What should I do in this situation? ([In CI, Java 17 is set](https://github.com/apache/incubator-seata/blob/2.x/.github/workflows/spotless-check.yml#L35-L39), so there is no problem.)

Comment (funky-eyes) [reply tm/src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java:422]: > ### Java 11 (Has Error ❌)
> ```shell
> $ sdk use java 11.0.27-librca 
> $  ./mvnw spotless:check 
> 
> [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:check (default-cli) on project seata-tm: The following files had format violations:
> [ERROR]     src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java
> [ERROR]         @@ -290,7 +290,7 @@
> [ERROR]          ················break;
> [ERROR]          ············case·TimeoutRollbacked:
> [ERROR]          ············case·Rollbacked:
> [ERROR]         -············//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
> [ERROR]         +················//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
> [ERROR]          ············case·Finished:
> [ERROR]          ················code·=·TransactionalExecutor.Code.RollbackDone;
> [ERROR]          ················break;
> [ERROR] Run 'mvn spotless:apply' to fix these violations.
> ```
> 
> ### Java 17 and above (✅)
> ```shell
> $ sdk use java 17.0.16-librca (java 21, java 25 OK)
> $  ./mvnw spotless:check 
> 
> [ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.44.3:check (default-cli) on project seata-tm: The following files had format violations:
> [ERROR]     src/main/java/org/apache/seata/tm/api/TransactionalTemplate.java
> [ERROR]         @@ -290,7 +290,7 @@
> [ERROR]          ················break;
> [ERROR]          ············case·TimeoutRollbacked:
> [ERROR]          ············case·Rollbacked:
> [ERROR]         -················//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
> [ERROR]         +············//·rollback·transactions·but·do·not·exist·are·usually·considered·completed
> [ERROR]          ············case·Finished:
> [ERROR]          ················code·=·TransactionalExecutor.Code.RollbackDone;
> [ERROR]          ················break;
> [ERROR] Run 'mvn spotless:apply' to fix these violations.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :seata-tm
> ```
> 
> This is the situation above, so there's no problem starting with Java 17 or later.
> 
> I have a problem with Java 11. And this happens unconditionally because the position of the comment changes.
> 
> What should I do in this situation? ([In CI, Java 17 is set](https://github.com/apache/incubator-seata/blob/2.x/.github/workflows/spotless-check.yml#L35-L39), so there is no problem.)

Have you consulted the Spotless community about how to resolve this issue?

**Review by YongGoose — COMMENTED** [review]
For now, I think it’s best to wait for a reply on this issue.
- https://github.com/diffplug/spotless/issues/2625

If no response comes for a long time, then we may need to proceed with running Spotless only on a specific version.

**Comment by funky-eyes** [comment]
According to the description in https://github.com/diffplug/spotless/issues/2625, we should drop JDK 11 and make JDK 17 the minimum required to run Spotless.

**Comment by JongminChung** [comment]
> According to the description in [diffplug/spotless#2625](https://github.com/diffplug/spotless/issues/2625), we should drop JDK 11 and make JDK 17 the minimum required to run Spotless.

@funky-eyes 
I saw your comment and worked on that [commit](https://github.com/apache/incubator-seata/pull/7644/commits/3b516178cf3f0f10386433cc9e466cb9d8457b0a). Please check.

**Review by funky-eyes — APPROVED** [review]
LGTM @YongGoose PTAL

**Review by YoWuwuuuw — APPROVED** [review]

File: pom.xml [hunk 2]
```diff
@@ -234,38 +234,18 @@
...
-            <properties>
-                <palantirJavaFormat.version>2.39.0</palantirJavaFormat.version>
+                <palantirJavaFormat.version>2.74.0</palantirJavaFormat.version>
             </properties>
         </profile>
         <profile>
-            <id>java11+</id>
+            <id>java17+</id>
             <activation>
-                <jdk>[11,)</jdk>
```
Comment (YongGoose) [inline pom.xml:268]: Why is this needed?

Comment (JongminChung) [reply pom.xml:268]: > I'm sorry for responding to your review too late.
>
> When I went on a long trip to Europe, I couldn't do the work because I couldn't take my laptop.

To. @YongGoose 

As you said, spotless is supported only for the version of spotless Java 17 or higher, so it seems that it is possible to remove the content that is applied to each profile differently from the previous one.
